### ISSUE TITLE
Provide troubleshooting measures for the automated import of PPPL SIPs into DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#135]
Currently the PPPL asynchronously uploads submission information packages to an Amazon S3 bucket for importing new DataSpace Items. A `cron` task parses a directory mount point for this S3 bucket and imports these into DataSpace when new Items are discovered.

Should this process fail, how best to identify and address these failures should be documented.

**Comment by kmcelwee** [comment]
PPPL's direct use of dataspace makes this ticket obsolete 🎉
