### ISSUE TITLE
Generate a report for the DataSpace PPPL data sets in the past six months of 2020

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#146]
A report for the PPPL Item imports should be generated for the past six months in order to gauge the usage and whether or not there are any failed imports.

**Comment by jrgriffiniii** [comment]
This was just raised as a higher priority Item during a meeting with the PRDS stakeholders held on 11/16/20. This report should focus upon the download frequency for Bitstreams.

**Comment by kmcelwee** [comment]
The download frequency report was generated
