### ISSUE TITLE
prioritize shibboleth auth

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/dspace-development#153]
Can we place the shibboleth login above the Dataspace User and Password (eliminate it altogether?) at the link below. 

https://oar.princeton.edu/mydspace
https://dataspace.princeton.edu/mydspace

replace/make it go to? 

https://oar.princeton.edu/shibboleth-login
https://dataspace.princeton.edu/shibboleth-login

**Comment by kmcelwee** [comment]
Dataspace was completed, OAR was not addressed.

**Comment by bess** [comment]
We believe this is no longer a user priority. @hhkitsune Would you please clarify?

**Comment by hhkitsune** [comment]
This is not currently a problem with OAR, so I will close the issue.
