### ISSUE TITLE
Introduce embargo restrictions at the level of Bitstreams

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#160]
Derived from #159, this feature request is to support embargo restrictions at the level of Item Bitstreams, rather than whole Items.

**Comment by kmcelwee** [comment]
Display the readme, but none of the data files. A group of researchers have asked for it three times. It's a reasonable request for research data.

- [ ] @kmcelwee will ask atmire to pursue this ticket.
- [ ] @kmcelwee add this feature to Phase II documentation
