### ISSUE TITLE
Troubleshoot the PPPL sync. issues for the DataSpace environments

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#167]
As reported by a user on 08/31/20, the Python-based synchronization for PPPL data sets is not being run daily.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-python/compare/jrgriffiniii-pppl-migration synchronizes on the `dev` environment, but this still does not detect new or modified files in the S3 bucket.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-python/commit/79a0ebc5c16cbbd12f7dc32b64a3f57b1d1a3ce0 finally ensures that this functions properly on the server.

**Comment by jrgriffiniii** [comment]
This was installed and tested on the `dev`, `staging`, and `production` server environments, and the following `cron` entry has been added:

```
0 * * * * source $HOME/pulibrary-src/dspace-python/pppl/scripts/pppl_pull 
```

**Comment by jrgriffiniii** [comment]
As there was a duplicate Item imported from the S3 Bucket, this required that I install the `dspace-jruby` and `dspace-cli` projects into the `staging` and `production` environments, and the delete the Item using these.

**Comment by jrgriffiniii** [comment]
There may still be an outstanding need to ensure that all contributors in the metadata are matched to DataSpace users, and to ensure that these users are e-mailed once the data set has been imported.

**Comment by jrgriffiniii** [comment]
This was found to still be error-prone on 10/22/2020, and https://github.com/pulibrary/princeton_ansible/pull/1791 was opened in order to more properly resolve this. I will need to please check throughout this week in order to ensure that the crontab job is running as expected.

**Comment by jrgriffiniii** [comment]
This should be reviewed once more before it is closed.

**Comment by jrgriffiniii** [comment]
Another incident has arisen for this, reported by a researcher user who cannot find an Item submission in the MyDSpace Task Pool.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/pull/1791/files did not update the necessary env. variables:

```
dspace@gcp-dataspace-prod1:~$ echo $AWS_ACCESS_KEY_ID
111111111111 # (this is *not* the access key ID)
```

**Comment by jrgriffiniii** [comment]
This seems to be why the crontab was failing; Further, there was also the following error:
```
[Fatal Error] dublin_core.xml:6:1006: The content of elements must consist of well-formed character data or markup.
org.xml.sax.SAXParseException; systemId: file:/home/dspace/pulibrary-src/dspace-python/pppl/s3/imports/fnespoli_Nespoli_NME_2020/item_000/dublin_core.xml; lineNumber: 6; columnNumber: 1006; The content of elements must consist of well-formed character data or markup.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at org.dspace.app.itemimport.ItemImport.loadXML(ItemImport.java:1953)
        at org.dspace.app.itemimport.ItemImport.loadDublinCore(ItemImport.java:1068)
        at org.dspace.app.itemimport.ItemImport.loadMetadata(ItemImport.java:1053)
        at org.dspace.app.itemimport.ItemImport.addItem(ItemImport.java:870)
        at org.dspace.app.itemimport.ItemImport.addItems(ItemImport.java:736)
        at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
org.xml.sax.SAXParseException; systemId: file:/home/dspace/pulibrary-src/dspace-python/pppl/s3/imports/fnespoli_Nespoli_NME_2020/item_000/dublin_core.xml; lineNumber: 6; columnNumber: 1006; The content of elements must consist of well-formed character data or markup.
```

**Comment by jrgriffiniii** [comment]
`$HOME/dspace/app_configs/dataspace` does contain the proper values set by https://github.com/pulibrary/princeton_ansible/pull/1791/files. I am setting the following in order to ensure that synchronized imports are successful:

```
0 * * * * source $HOME/dspace/app_configs/dataspace; export AWS_DEFAULT_REGION=us-east-1; aws s3 sync s3://pppldataspace $HOME/pulibrary-src/dspace-python/pppl/s3; source $HOME/pulibrary-src/dspace-python/pppl/scripts/pppl_pull.sh
```

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-development/issues/254 was noted by PPPL users during the last session in which they tested the new imports from DataSpace and the OAR. This should be prioritized for a SN@P ticket.

**Comment by kmcelwee** [comment]
PPPL adopted direct access to dataspace, this ticket is obselete 🎉
