### ISSUE TITLE
Fix the broken link for "Home" from the "About" tab on the navbar for the OAR theme

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#186]
As of 25 March this is fixed in dev and staging. Just waiting for the 26 March maintenance window to deploy to production.

**Comment by jrgriffiniii** [comment]
Please see https://git.atmire.com/clients/princeton-5/-/tree/oar-client-DEV/dspace-jspui for reference, as this is where the theme for the JSPUI should be modified.

**Comment by matthewjchandler** [comment]
Please note that the home button also does not work in DataSpace--not on any page.
