### ISSUE TITLE
Adjust the message wording for DataSpace e-mails when data set submissions are not accepted

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#188]
Currently the wording used is `rejected`, and this is not accurate, as the data sets are within a curatorial life cycle in which they are always consistently accepted (but, with some editorial changes).

**Comment by matthewjchandler** [comment]
# Rejection email message
#
# {0}  Title of submission
# {1}  Name of collection
# {2}  Name of the curator
# {3}  Reason for the 'rejection' action
# {4}  Link to 'My DataSpace' page
#
Subject: DataSpace Submission Returned for Revision

You submitted: {0}

To collection: {1}

Your submission has been returned for revision by {2}
with the following notes:

{3}

Your submission has not been deleted.  You can access it from your
"My DataSpace" page: {4}

If you have any questions, please contact the DataSpace curators at dspadmin@princeton.edu.

**Comment by matthewjchandler** [comment]
Sorry, apparently I don't understand how to properly format a GitHub issue comment. At any rate, I think the above gives you the language you need @kmcelwee
