### ISSUE TITLE
Support CSV files for DataSpace Bitstream formats

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#189]

**Comment by kelynch** [comment]
This can be handled in the admin UI.  I added this on dev, and confirmed with Matt that it works.  Matt confirmed also that he has admin rights to do this on production as needed.  I believe we can consider this issue resolved.

**Comment by kmcelwee** [comment]
Double checked with Matt that no further action is needed. Closing this issue, thanks @kelynch !
