### ISSUE TITLE
Document workflow for ETD ingestion and management in DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#19]
Currently graduate-level dissertations and certain research publications are published into https://dataspace.princeton.edu/jspui/handle/88435/dsp01td96k251d

This community is actually provided with metadata provided by a third-party vendor (ProQuest), and the work flow for managing these is unique to this community (various Python and `tcsh` scripts are used, along with file transfers over the FTP)

**Comment by kmcelwee** [comment]
We did this ! 🎉
