### ISSUE TITLE
Display Community and Collection together

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#192]
In multiple locations, ranging from the public-facing metadata field "Appears in Collections" to the new item submission notifications sent to admins, only the item's collection is displayed. We have lots of collections called "Research Data Sets" or something similar, so it's really only helpful to be able to see the community and collection listed together.

**Comment by hhkitsune** [comment]
This would require significant development in DataSpace. We would prefer to dress this in PDC Discovery and the new build.
