### ISSUE TITLE
Present suggested full citation on item pages

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#193]
May require manual input, which we curators can manage. The important thing is that a citation is shown prominently on public-facing item pages.

**Comment by kmcelwee** [comment]
- [ ] @kmcelwee Speak to Atmire about autogenerating citations from metadata
- [ ] @kmcelwee If impossible, place existing citation metadata at the top of record page.

**Comment by hhkitsune** [comment]
Looking for clarification on this ticket. Hannah will talk to you in your meeting tomorrow. @matthewjchandler

**Comment by matthewjchandler** [comment]
I believe this is being accomplished in the development of PDC Discovery, including the MVP. Let me know if more discussion is needed @hhkitsune

**Comment by hhkitsune** [comment]
@matthewjchandler Thank you! I will close the issue at this time, but we can discuss this topic further in our meetings.
