### ISSUE TITLE
Generate an embargo report for the DataSpace Senior Theses Items

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#198]
This should include the policies for the Bitstreams for DataSpace Items within the 2020 Senior Theses Community.

**Comment by jrgriffiniii** [comment]
The report generated from the production environment can be found here: https://drive.google.com/file/d/1yy7SDzdqzlkLMK5Tr19Zh1IxAHOzBgwh/view?usp=sharing

**Comment by kelynch** [comment]
This is complete, closing.
