### ISSUE TITLE
There is a discrepancy between Student Theses Items in the Creative Program for the staging and production environments

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#200]
Currently there are 303 Items indexed in the staging environment: https://dataspace-staging.princeton.edu/handle/88435/dsp01gx41mh91n and only 299 Items in the production environment: https://dataspace.princeton.edu/handle/88435/dsp01gx41mh91n

When inspecting these using the DSpace CLI, I found that there was a much larger discrepancy, with 300 Items being stored in the production environment and 328 in the staging environment for this Collection.

**Comment by kelynch** [comment]
We are working to address this by mirroring production database data and Solr index to staging, to have two identical environments to work with.

**Comment by jrgriffiniii** [comment]
This discrepancy looks to have been resolved by a synchronization undertaken by the operations team.
