### ISSUE TITLE
Document the theming for DataSpace and create a new repository for the JSPUI theme

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#222]
@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/75)

Where does the theme customization currently reside? This should probably be a separate GitHub repository, but I also don't wish to create a number of new repositories.

---

@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-634102102)

I could not find any repositories on https://bitbucket.org/princeton/ which might hold this.

---

@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-634104716)

On the dataspace.princeton.edu server, subdirectories within `/dspace` do have the custom theme included within `/dspace/webapps/jspui/`, but this is *not* tracked within a git repository.

---

@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-634106619)

`/usr/local/DR/home/dspace/dspace.git` is a git repository, with commit logs indicating that this has been pushing to the remote for https://github.com/PrincetonUniversityLibrary/dspace. However, it also seems to be the case that this code base is shared for the OAR.

---

@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-634111371)

The JSP files are located within `/usr/local/DR/home/dspace/dspace.git/dspace-jspui/src/main/webapp`, where the theme has been implemented by overriding the JSPUI theme, and the files are tracked on the `dataspace` branch of the git repository.

---

@jrgriffiniii commented on [Wed May 27 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-634935780)

https://github.com/pulibrary/dataspace-jspui was created, along with source files (after they have been audited for hard-coded e-mail addresses, names, and IP addresses).

---

@jrgriffiniii commented on [Thu Jun 18 2020](https://github.com/pulibrary/dspace-cli/issues/75#issuecomment-646225028)

This is blocked by the inability to build and deploy this within the Docker environment. Currently, only the custom footer is rendered:

![image](https://user-images.githubusercontent.com/1443986/85056619-83435100-b16d-11ea-84b4-90ae7eff21df.png)

**Comment by jrgriffiniii** [comment]
When I was last advancing this, there were a number of issues affecting the Maven build process in my local environment. This required the following changes, but DataSpace can now be built for Docker or Vagrant environments: https://git.atmire.com/clients/princeton-5/-/compare/dataspace-client-DEV...jrg5-dataspace-local-dev-build

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-development/compare/spike-jrgriffiniii-atmire was needed in order to build DataSpace locally, but this does indeed work now. I'm going to proceed with testing this for the OAR.

**Comment by jrgriffiniii** [comment]
Throughout the past month, there has only been one request for this:
![image](https://user-images.githubusercontent.com/1443986/100918387-65ad3e00-34a6-11eb-8e50-6cd0e532c8f6.png)

**Comment by kmcelwee** [comment]
How we've incorporated PrincetonUniversityLibrary/dataspace into our workflow obviates this I think (?)
