### ISSUE TITLE
Status of dspace-operations

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#225]
@jrgriffiniii commented on [Thu May 21 2020](https://github.com/pulibrary/dspace-cli/issues/70)

https://github.com/princetonuniversitylibrary/dspace-operations is privately-accessible - it should probably remain so, but perhaps this should be synchronized with BitBucket commits and archived.

**Comment by kmcelwee** [comment]
dspace-operations has been archived.
