### ISSUE TITLE
Document the process of ingesting large-scale datasets into DataSpace on behalf of researchers

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#226]
@jrgriffiniii commented on [Mon May 04 2020](https://github.com/pulibrary/dspace-cli/issues/11)

Currently we cannot support the ingestion of data sets beyond 250MB for public download into DataSpace collections due to storage and server configuration restrictions. As a consequence, we have recently started to use Dropbox as an alternative storage solution for larger scale datasets, providing public users with the ability to directly download the datasets for any given Item.

**Comment by matthewjchandler** [comment]
PRDS now has published guidelines on our website: https://researchdata.princeton.edu/research-lifecycle-guide/publishing-large-datasets

**Comment by kmcelwee** [comment]
We have Globus and PRDS now ✅🎉
