### ISSUE TITLE
Provide documentation for the various batch administration tasks performed on behalf of users

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#229]
This is a fairly lengthy issue, and builds heavily upon the existing documentation both here: https://docs.google.com/document/d/108hlHrnQS_ORuAWyHg5VkKGJuWgp31myW-WquxhYWu8/edit and https://docs.google.com/document/d/1ZypRW_j1L49gZE-wHorCuOHkM7v97eAdMQwuQ0keya8/edit

**Comment by kmcelwee** [comment]
We did it 🎉
