### ISSUE TITLE
How should DataSpace handle the versioning of data sets?

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#233]
@jrgriffiniii commented on [Mon May 18 2020](https://github.com/pulibrary/dspace-cli/issues/59)

This was enquired by Wind Cowles, one of the Product Owners for DataSpace, which, paraphrased in my own language was:

```
if we need to correct something in a dataset, will we need to re-upload the corrected version as a new dataset, or is there the option to create a new version of the dataset?
```

---

@jrgriffiniii commented on [Mon May 18 2020](https://github.com/pulibrary/dspace-cli/issues/59#issuecomment-630371270)

This is listed as a feature which is supported by DSpace 5.x releases: https://wiki.lyrasis.org/display/DSDOC5x/Item+Level+Versioning

**Comment by kmcelwee** [comment]
Proposals to address this problem are being tracked in this Google doc:
https://docs.google.com/document/d/13ibT_OhCpgyW66asKcn_cASqQkJ8ArGv8qV6vnq0Q50

**Comment by kmcelwee** [comment]
### Conclusion

> There remains no industry standard for versioning large datasets. In 2015 the Research Data Alliance interviewed 33 organizations including NASA and Zenodo, and found 33 different workflows. They pursued some kind of standard process for 4 years and, from my reading, were still unable to delineate clear guidelines.
>
> PRDS’s goals are to enact a data versioning workflow more open and rigorous than any of our peers, wanting every version properly cited and quickly downloadable through a GUI, without sacrificing storage efficiency. But Globus and Git, the two pieces of software necessary for efficient data transfer and version storage, have not been combined anywhere.
>
> PRDS’s goals aren’t unique to Princeton, giving DRDS the unique opportunity to build that infrastructure if given significant developer time and if it were made a singular priority. Combining S3 versioning, the Globus CLI and Python SDK, and Git LFS, there may be a path forward to create a user interface that points directly to the version requested, but that would require a significant amount of custom infrastructure, with no promise of success. If successful, however, we’d be solving a problem central to many of our peers.
>
> In the short term, there exists no way to efficiently store versioned items in Globus in a user-friendly way. PRDS will need to determine priorities. Assuming strict adherence to their own standards, either (a) they can store datasets inefficiently, and simply double their datasets for each version, or (b) use git to version their datasets and provide documentation allowing users to checkout earlier versions of the dataset.
