### ISSUE TITLE
Improve the documentation for adding users to departments in DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#234]
@kmcelwee commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/72)

Matt Chandler approached me with a request to add Valerie Ching `vching` to the “Industrial Relations Section” (IRS) community’s “Working Papers” collection. 

Following instructions laid out in [DataSpace Operations.](https://docs.google.com/document/d/108hlHrnQS_ORuAWyHg5VkKGJuWgp31myW-WquxhYWu8/edit#heading=h.hzpydio2tcem),
I ssh-ed into dataspace, navigated to `~dspace/princeton_library`, and ran the executable to create `vching` as a submitter.

Whereas old documentation seems to suggest that the Industral Relations Section would have an administrator that would add Valerie to their collection, Matt doesn’t think that’s the case. Furthermore, in [Google Docs - DSpace Repository Operations](https://docs.google.com/document/d/1jqnirSkecDeXyNrltLilBt1i7AJxrO9rMqxsb6oInXY/edit#) the following note was left by Monika:

> Original plan was to affiliate Users with departmental collections such that they can perform the Edit/Archive Step. Currently setup everybody to see all submissions for all collections 

This was OAR-specific, however, and when I attempted to add myself as a submitter and submit a paper to IRS in DataSpace, I was given a server error. Presumably, Valerie would be in a similar position.

We need to:
- Figure out whether it’s our responsibility to add Valerie as an IRS submitter.
- If it is our responsibility, figure out how to give her permission to submit to IRS
- Document more clearly in the Google Docs listed above to prevent future slipups.

---

@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/72#issuecomment-634090847)

How I have been approaching this is through the following steps on the user interface:

- Finding the Collection (within the Community) where the user should have submission (and *not* admin.) privileges:
![image](https://user-images.githubusercontent.com/1443986/82917891-ffb58c00-9f41-11ea-8402-d85bd0658f7c.png)
- Browsing to the Collection view page, and selecting "Edit Submitters"
![image](https://user-images.githubusercontent.com/1443986/82918093-3c818300-9f42-11ea-9ffd-5bb83612871b.png)
- Using "Select E-people", select the user and add them to the Group:
![image](https://user-images.githubusercontent.com/1443986/82918246-70f53f00-9f42-11ea-8316-b83b09727b78.png)

**Comment by kmcelwee** [comment]
I have created a google doc that walks our stakeholders through this process: https://docs.google.com/document/d/1FodEsGNwPU_NuMvfZsctlg6yq_dryvIDKJH2TqmrpMo/edit
