### ISSUE TITLE
Ensure that we have access to the SharePoint departmental permissions website at the University-level

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#238]
@jrgriffiniii commented on [Mon Jun 15 2020](https://github.com/pulibrary/dspace-cli/issues/89)

This should be accessible by all PUL ITIMS members here: https://sp2016.princeton.edu/our/strar/Requests/Forms/2020.aspx

**Comment by kmcelwee** [comment]
James, Bess, Kate, and I have access ✅
