### ISSUE TITLE
Document how Symplectic Elements interfaces with the OAR

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#240]
@jrgriffiniii commented on [Mon May 04 2020](https://github.com/pulibrary/dspace-cli/issues/8)

Currently faculty and research publications are managed by members of the Scholarly Communications Office using an installation of Symplectic Elements (hosted by OIT on https://oaworkflow.princeton.edu - please be aware that one needs to be authenticated over the VPN in order to access this server).

How items are released from Elements and ingested into the OAR should be documented, along with general guidance regarding potential errors which can arise when interfacing with these systems.

**Comment by jrgriffiniii** [comment]
The REST API documentation introduced in https://github.com/pulibrary/dspace-development/pull/349 advances some of this, but there may be some additional points which must be outlined or described.

**Comment by bess** [comment]
We think this work is better served by having a conversation with the elements vendor.
