### ISSUE TITLE
Identify where to store the DataSpace configuration files

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#244]
@jrgriffiniii commented on [Tue May 26 2020](https://github.com/pulibrary/dspace-cli/issues/78)

This has normally been tracked in https://github.com/pulibrary/princeton_ansible, and secrets management would be required for certain configuration settings.

---

@jrgriffiniii commented on [Thu May 28 2020](https://github.com/pulibrary/dspace-cli/issues/78#issuecomment-635511405)

https://github.com/pulibrary/princeton_ansible/issues/512 was the issue which I originally created for this.

---

@jrgriffiniii commented on [Mon Jun 15 2020](https://github.com/pulibrary/dspace-cli/issues/78#issuecomment-644293573)

This should build upon https://github.com/pulibrary/dspace-development/tree/master/ansible/roles/pulibrary.dspace/tasks, and ensure that secrets are managed using `ansible-vault`.

**Comment by kmcelwee** [comment]
It seems like these have ultimately been stored in Atmire's gitlab repo, and then when we want to share it with stakeholders, it's just been placed in PrincetonUniversityLibrary
