### ISSUE TITLE
Update the "request a copy" button for requesting items in DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#249]
@jrgriffiniii commented on [Tue Jun 16 2020](https://github.com/pulibrary/dspace-cli/issues/92)

It is not necessarily clear that end-users need to be authenticated over the VPN in order to request a physical copy of a DSpace item. This should be more clear to users.

**Comment by kmcelwee** [comment]
PRDS is unfamiliar with this request, presumably this is a request from Lynn

**Comment by kmcelwee** [comment]
Double checking with Lynn revealed that a change is no longer needed.
