### ISSUE TITLE
E-mail notifications are not being generated for PPPL package imports from the AWS S3 Bucket

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#252]
Packages might be being properly imported into DataSpace, however, PPPL Collection administrators are not being e-mailed when the packages are successfully imported and marked for review.

**Comment by jrgriffiniii** [comment]
This needs to be given a higher priority, I will reserve time to begin addressing this tomorrow (12/10/20)

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-python/compare/jrgriffiniii-refactor-autumn-2020...jrgriffiniii-fix-email introduces more of a refactor for the PPPL data set importation, with https://github.com/pulibrary/dspace-python/commit/aa841755bcadec62983af2d622e53d634e43d1db fixing the synchronization with AWS S3 using https://boto3.amazonaws.com/v1/documentation/api/latest/index.html

**Comment by jrgriffiniii** [comment]
This is still affecting PPPL users, but there have been some cases in which the users are successfully notified by DataSpace in e-mail exchanges with me.

**Comment by kmcelwee** [comment]
PPPL's direct use of dataspace makes this ticket obsolete 🎉
