### ISSUE TITLE
Authentication attempts over Shibboleth for DataSpace and the OAR yield `Web Login Service - Stale Request` errors

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#254]
If one attempts to authenticate, logout, and then re-authenticate for either DataSpace or the OAR, then one encounters the following error:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/3a846bd5-e78d-4092-b349-a068905e0553)

This affects multiple users, and currently the only solution in place is to direct users to open multiple incognito browser sessions, with one attempt eventually establishing a new request. This, most likely, will involve direct support from the OIT.

**Comment by jrgriffiniii** [comment]
A support request with the OIT has been created with https://princeton.service-now.com/service?id=ticket&table=task&sys_id=878b4d1c1b4d2010435885d56b4bcb5b

**Comment by jrgriffiniii** [comment]
The following configuration setting for `relayd` was primarily affecting this:

```conf
# filters
http protocol httpsfilter {
# [...]
    match response header set "Cache-Control" value "max-age=$VALUE"
# [...]
```

Further, there were some adjustments to the `shibd`, `nginx`, and `httpd` configuration, but this may simply have improved performance.

**Comment by jrgriffiniii** [comment]
I must draft some more definitive information for this, but there is a meeting later today with a user who experienced problems which might have some additional information.

**Comment by kmcelwee** [comment]
This was fixed 🎉at least as far as I am aware 😄
