### ISSUE TITLE
DataSpace Bitstreams for certain Items cannot be downloaded

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#259]
Please see https://dataspace.princeton.edu/handle/88435/dsp01nc580q118?mode=simple for an example.

**Comment by jrgriffiniii** [comment]
The database records do not yield any metadata for the related Bitstreams and Bundles with NULL values.

**Comment by jrgriffiniii** [comment]
https://git.atmire.com/clients/princeton-5/-/blob/dataspace-client-DEV/dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/ItemTag.java#L976 is where the Bitstream title is not being rendered.

**Comment by jrgriffiniii** [comment]
I could not diagnose precisely why this was occurring (perhaps the caching in https://git.atmire.com/clients/princeton-5/-/blob/dataspace-client-DEV/dspace-api/src/main/java/org/dspace/content/DSpaceObject.java#L1249 is problematic? I have seen this trigger anomalies once before). However, editing the Bitstream metadata using the Item Edit Form looks to be the solution.

**Comment by jrgriffiniii** [comment]
This was fixed in the production environment, and shared with the reporting user for feedback.

**Comment by kmcelwee** [comment]
It seems like Globus solved this issue. (per @matthewjchandler)
