### ISSUE TITLE
Provide backups to Amazon S3 buckets for the thesis-central production

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#263]
Please see https://gist.github.com/jrgriffiniii/cf6a7231aa0d37c53f4dee691c17cd90 for an outline of the tasks in this procedure.

**Comment by jrgriffiniii** [comment]
This has been completed for the file attachments and Solr indices. I will need to upload the DataSpace SIPs from my local development environment.

**Comment by kmcelwee** [comment]
I believe all necessary data has been transfered
