### ISSUE TITLE
DataSpace user draine needs to be deprecated in favor of user draine[at]astro

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#272]
Earlier today, PRDS and I were notified that a faculty member has been using the non-Shibboleth login link in order to authenticate into DataSpace with a legacy password for the account `draine`. In response to some user interface errors which may have been triggered by this, it was discovered that using the Shibboleth SSO created a new user account `draine[at]astro`. Item submissions and privileges should be transferred to this new account.

**Comment by jrgriffiniii** [comment]
Item submissions should be transferred for the production environment, and common group membership should ensure that both accounts have identical privileges.

For the purposes of ensuring that no anomalous behavior persists, I am also going to disable access for the `draine` account. I shall also update the user who reported this.

**Comment by kmcelwee** [comment]
No adverse behavior has been reported in three months. Closing for now.
