### ISSUE TITLE
Updating submission forms to reflect industry standards

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#273]
PRDS is creating appropriate forms for the collections that they curate. @matthewjchandler will change the existing XML file, publish to @kmcelwee private repo, and @kmcelwee will deploy it.

**Comment by kmcelwee** [comment]
PRDS has made the pull request: https://github.com/PrincetonUniversityLibrary/dataspace/pull/1

**Comment by bess** [comment]
This has been deployed to dataspace-dev. @matthewjchandler is reviewing it there and is going to make a few more changes.

**Comment by bess** [comment]
This has been deployed to production and approved by PRDS.
