### ISSUE TITLE
`null` Bitstreams are appended (erroneously) for DataSpace Items

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#277]
This was initially reported by a member of the Princeton Research Data Service, referencing the following three Items:

- http://arks.princeton.edu/ark:/88435/dsp01kp78gj856
- http://arks.princeton.edu/ark:/88435/dsp018049g752g
- http://arks.princeton.edu/ark:/88435/dsp01cr56n346x

**Comment by jrgriffiniii** [comment]
It appears that there are cases where the Bitstream uploads failed to process, please see https://dataspace.princeton.edu/bitstream/88435/dsp01kp78gj856/3/ and https://dataspace.princeton.edu/handle/88435/dsp01kp78gj856

**Comment by jrgriffiniii** [comment]
Using ad-hoc queries in PostgreSQL, I am finding that there are Bitstreams missing for these Items.

**Comment by jrgriffiniii** [comment]
The Bundles do exist for the case of https://dataspace.princeton.edu/handle/88435/dsp01kp78gj856:

- 98533
- 98567
- 98566

**Comment by jrgriffiniii** [comment]
Updating the Bitstream metadata seems to have fixed these Item records. I shall proceed with contacting the reporting user in order to identify any other outstanding Items.

**Comment by kmcelwee** [comment]
#289 and #284 got the full scope of this problem, and this the problem at large is being addressed by Francis and Atmire
