### ISSUE TITLE
Create list of empty bitstream filenames

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#284]
Either through the REST API or database, create a list of all bitstreams that don't have a filename. Include the parent item / handle in the ultimate spreadsheet. We are uncertain how this problem appeared; it may have been human error. (currently don't have an example)

I’m looking at all this DB diagram, and I’m not seeing where bitstream filenames are stored: https://wiki.lyrasis.org/display/DSDOC6x/Storage+Layer?preview=/68069687/78157937/dspace6.png
DSpace stores all its files in a 38-digit ID but I don’t exactly know where that mapping takes place.

Update from DSpace Slack: it's stored in the `metadatavalue` table!

**Comment by kelynch** [comment]
Here's an example from staging:

https://dataspace-staging.princeton.edu/handle/88435/dsp014q77fs42v

Note that it's been fixed on prod.

**Comment by kmcelwee** [comment]
This was quite the investigation!

The query
`select * from metadatavalue where resource_type_id = 0 and text_value IS NULL;`
returned no results for both the staging and dev server.

The query  `select * from metadatavalue where resource_type_id = 0 and text_value = '';` showed 1 result on the staging server, and 0 results on the dev server. Lynn corrected this entry. ([Staging](https://dataspace-staging.princeton.edu/handle/88435/dsp01c821gn25b), [Dev](https://dataspace-dev.princeton.edu/handle/88435/dsp01c821gn25b))

Working backwards from the example provided revealed that the problem wasn’t filenames that were NULL, but bitstreams that didn’t have a `dc.title` field, which is `resource_id` 64. **On the prod server there are 619 items that fall in this category.** They've been placed into this google sheet: 
https://docs.google.com/spreadsheets/d/1LhDt9ppgX_Q3uCqKhr3HZieLq12-Up1DlmQW5JrjxF8/edit?usp=sharing

Here is the query:
```sql
SELECT handle,bitstream_id
FROM handle 
INNER JOIN item ON (item.item_id = handle.resource_id)
INNER JOIN item2bundle ON (item.item_id = item2bundle.item_id)
INNER JOIN bundle2bitstream ON (item2bundle.bundle_id = bundle2bitstream.bundle_id)
WHERE bitstream_id IN (
     SELECT resource_id
     FROM metadatavalue WHERE resource_type_id = 0 
     GROUP BY resource_id 
     HAVING NOT (64 = ANY(ARRAY_AGG(metadata_field_id)))
);
```

I'm moving away from this for now, but I would imagine we might want to figure out what our next steps are? I can include collection / community information so that we know what's exclusively Lynn's concern? Some of the metadata includes import information, from which we can grab filenames, so fixing this may be automatable. 

Side note: There were 635 on dev, 20 on staging, and (as mentioned above) 619 on prod. How exactly are dataspace databases being synced?
