### ISSUE TITLE
Provide a link to the documentation for Collection renaming policy (and general collection mgmt. requests)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#29]
This should link directly to the inventory on Google Drive: https://docs.google.com/document/d/1auUb7yIzGVMXeKsKh6MwQhsqDZexuqUhroAoiGOCR9c/edit

**Comment by kmcelwee** [comment]
Would you mind expanding on what this ticket means if it's still applicable? I recognize that since July 2020, it has probably changed.

**Comment by jrgriffiniii** [comment]
This is deprecated and no longer a lengthy or complex process.
