### ISSUE TITLE
For 2021 thesis loading: Strip qualifiers from Computer Science department submissions

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#294]
This is a note for the 2021 Senior Thesis upload process.  Computer Science thesis submissions from Vireo will include one of the following qualifiers in the program name:

```
Computer Science (BSE)
Computer Science (AB)
```

The `(BSE)` and `(AB)` qualifiers will need to be removed before the submissions are uploaded to DataSpace, in order to match DataSpace's department value for Computer Science.

**Comment by bess** [comment]
This is done in the `vireo_transformation` code: 

See https://github.com/pulibrary/vireo_transformation/blob/main/lib/etd_transformer/vireo/submission.rb#L74-L83
