### ISSUE TITLE
Task Pool entries are not created consistently for users with curatorial permissions for DataSpace in the production environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#301]
One PPPL user *did* confirm that the task was created for a submitter user, but this is still not consistently applied for all users.

**Comment by kmcelwee** [comment]
Is this obviated now because of the new workflow? Or is this still a problem?

**Comment by jrgriffiniii** [comment]
This has been updated, I apologize for overlooking this.

**Comment by jrgriffiniii** [comment]
This was not really specific to PPPL users, as other users are definitely affected.

**Comment by jrgriffiniii** [comment]
I am pretty certain that this is triggered by the adding or updating users to administrative groups in relation to a specific Collection. In cases where an Item is submitted before a user is added to a curatorial group in which they would have received a submission task in the task pool, should the user be added *after* the Item is submitted, the Task is not created.

**Comment by jrgriffiniii** [comment]
This has been identified as a long-standing bug which cannot be resolved without a migration to DSpace 6 or DSpace 7 releases.
