### ISSUE TITLE
Get Bess set up with RSA token and email 

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#310]
- [ ] Search closed tickets from the summer of 2020 for instructions / documented hurdles for acquiring RSA token
- [ ] Locate existing documentation for working with RSA tokens / passcodes ezproxy. Centralize documentation into dspace-development if necessary.
- [ ] Ensure that she can tunnel / ssh on the dataspace sftp server.

**Comment by kelynch** [comment]
Instructions for setting up an RSA token here: https://docs.google.com/document/d/1EuKctKDtRQrspwV_knfzYylLULpjJV_usU9UxSUM6hk/edit#

**Comment by kmcelwee** [comment]
Our ownership of the sftp server will obviate this.
