### ISSUE TITLE
June 2019 Dissertation missing entries and duplication

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#315]
There appear to be three dissertations missing from DataSpace from the June 2019 delivery that came in the June 2019 ProQuest load:
* World Observation : ‡b  Ito Chuta and the Making of Architectural Knowledge in Modern Japan, Volume I., Mullane, Matthew., [BIB 12043058](https://catalog.princeton.edu/catalog/12043058)
* Electrochemical Reduction of Carbon Dioxide on Zinc Antimonide and Developing of Catalytic Conductance for Benchmarking Electrocatalysts. By Zhang, Tao, [BIB 12043057](https://catalog.princeton.edu/catalog/12043057)
* Trustguard : ‡b A Model for Practical Trust in Real Systems. By Stephen R. Beard. [BIB 12043059](https://catalog.princeton.edu/catalog/12043059)

All three have bib records but no arks associated with them.

There is also a dissertation from June 2019 that was loaded twice:
* [First instance](https://dataspace.princeton.edu/handle/88435/dsp01ng451m386)
* [Second instance](https://dataspace.princeton.edu/handle/88435/dsp019019s539k)

**Comment by jrgriffiniii** [comment]
I suspect that this may be an error from updates which were issued when I was not directly involved in updating the Voyager ILS records.

**Comment by jrgriffiniii** [comment]
I have been searching through the downloaded ZIP-compressed files using `zipgrep`, and I have failed to find these titles. I will look to manually decompress the files and check the metadata within.

**Comment by jrgriffiniii** [comment]
The following ZIP file must be transformed and ingested:

* etdadmin_upload_666311.zip (this maps to BIB 12043058)

BIB 12043057 could not be resolved to a ZIP file.

**Comment by kelynch** [comment]
Lynn has requested the following to be re-uploaded from ProQuest to the FTP server:

* World Observation: Itō Chūta and the Making of Architectural Knowledge in Modern Japan, Volume I by Mullane, Matthew, Princeton University, 2019, 560 pages; 13887031
* Electrochemical Reduction of Carbon Dioxide on Zinc Antimonide and Developing of Catalytic Conductance for Benchmarking Electrocatalysts | by Zhang, Tao, Princeton University, 2019, 127 pages; 13886930
* Trustguard: A Model for Practical Trust in Real Systems | by Beard, Stephen R., Princeton University, 2019, 117 pages; 13887108

**Comment by jrgriffiniii** [comment]
I have withdrawn https://dataspace.princeton.edu/handle/88435/dsp019019s539k, and can look to investigate whether or not the ProQuest packages have been uploaded to the FTP server.

**Comment by jrgriffiniii** [comment]
I apologize, I could not locate any new uploads on the SFTP server:

```bash
sftp> ls -lt
-rw-r--r--    1 98041    pusvc      923414 Apr 21 22:09 etdadmin_upload_802537.zip
-rw-r--r--    1 98041    pusvc    35713525 Apr 21 22:09 etdadmin_upload_801665.zip
-rw-r--r--    1 98041    pusvc     8234894 Apr 21 22:09 etdadmin_upload_801544.zip
-rw-r--r--    1 98041    pusvc    54737987 Apr 21 22:09 etdadmin_upload_801413.zip
-rw-r--r--    1 98041    pusvc     6684803 Apr 21 22:09 etdadmin_upload_800895.zip
-rw-r--r--    1 98041    pusvc     1942819 Apr 21 22:09 etdadmin_upload_800891.zip
-rw-r--r--    1 98041    pusvc    32208311 Apr 21 22:09 etdadmin_upload_800557.zip
-rw-r--r--    1 98041    pusvc    67234204 Apr 21 22:09 etdadmin_upload_800361.zip
-rw-r--r--    1 98041    pusvc     6352751 Apr 21 22:09 etdadmin_upload_800286.zip
-rw-r--r--    1 98041    pusvc    12020734 Apr 21 22:09 etdadmin_upload_798798.zip
-rw-r--r--    1 98041    pusvc    17637625 Apr 21 22:09 etdadmin_upload_798765.zip
-rw-r--r--    1 98041    pusvc    14167070 Apr 21 22:09 etdadmin_upload_796399.zip
```
