### ISSUE TITLE
Reuse handles for exported items when importing to another DSpace instance

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#327]
Blocks #316 

Using the import/export CLI tools in DSpace 5.x to migrate objects from one DSpace 5.x instance to another works mostly as expected, however the handle included in the `handle` file in the exported item isn't be reused in the other DSpace instance, and instead a new handle is being created when it's imported.  Is there a way to export items with handles from one DSpace instance and import them to another while preserving the same handle?  

According to the documentation, this should be possible - https://wiki.lyrasis.org/display/DSDOC5x/Importing+and+Exporting+Items+via+Simple+Archive+Format

**Comment by jrgriffiniii** [comment]
This has been deprecated by PDC Describe.
