### ISSUE TITLE
Shift dataspace sftp server away from OIT infrastructure 

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#329]
Proquest contact: 1-800-521-0600 ext. 2; disspub@proquest.com
We just have to call them and give them a new hostname and credentials. Preferaby we could have them post to Google Cloud Storage.
Francis wants to use SSH key instead of login and password. Ask Haley at proquest for a public ssh key.

**Comment by kmcelwee** [comment]
Haylie was contacted, and our case number is 04370188. She is checking with her development team to see if a public ssh key can be provided.

**Comment by kelynch** [comment]
ProQuest technical support receives the following error when trying to connect to the new pulcloud server - 

```
Connecting to XXX.pulcloud.io...
ssh: connect to host XXX.pulcloud.io port 22: Connection timed out"
```

**Comment by bess** [comment]
We have theses being transferred to the new SFTP server now!!
