### ISSUE TITLE
Shift latest PRDS metadata to dataspace

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#339]
The following PRs need to be deployed to dataspace
* https://github.com/PrincetonUniversityLibrary/dataspace/pull/7
* https://github.com/PrincetonUniversityLibrary/dataspace/pull/1

Synchronizing this repo with gitlab is also important: https://github.com/PrincetonUniversityLibrary/dataspace/issues/6

**Comment by bess** [comment]
These are now in production.
