### ISSUE TITLE
Department of Geosciences / Research Data Sets Collection Items aren't available on the Task Pools for Users

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#342]
This was reported by a Princeton Data Research Service user.

**Comment by jrgriffiniii** [comment]
This may be resolved, by I need to first confirm that this before closing the issue.

**Comment by bess** [comment]
@hhkitsune Will follow up and see if this still needs attention.

**Comment by matthewjchandler** [comment]
I just ran a test, and I'm not seeing this as an issue as of 2022-01-24, so I think it can be closed (per conversation with @hhkitsune )

**Comment by hhkitsune** [comment]
Per Matt's feedback, I'm closing this issue for now with the understanding that the issue could possibly occur in the future.
