### ISSUE TITLE
Create redirects from DataSpace to OAR for migrated collection

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#346]
References #316 

A total of 55 tems in the LISD collection will be migrated from DataSpace to the OAR; new ark identifiers will be minted due to a limitation of customized handle management in the OAR code base.

EZID URL redirects will be managed separately.  This will create tombstone URLs at DataSpace that will need to be redirected to the OAR record instances. 

Example (test item in DataSpace-Dev):
<img width="1095" alt="Screen Shot 2021-05-24 at 9 57 33 AM" src="https://user-images.githubusercontent.com/7795797/119358366-88aaf480-bc76-11eb-8854-84d1e72ede7c.png">

The ark URL redirects correctly: 
http://arks.princeton.edu/ark:/99999/fk4h435r53

However the tombstone URL remains: 
https://dataspace-dev.princeton.edu/handle/99999/fk4h435r53

The DataSpace tombstone URLs should redirect to the ark URL.

Real-world example: 
This https://dataspace.princeton.edu/handle/88435/dsp018w32r8403 should redirect to https://oar.princeton.edu/handle/88435/pr1dn8c

**Comment by kelynch** [comment]
@kayiwa Here is the issue in DSpace dev referring to ark redirects from dataspace to oar.  Should this be added to princeton_ansible instead?

**Comment by bess** [comment]
Done!
