### ISSUE TITLE
Import French and Italian theses to dataspace prod

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#370]
When completed, don't forget to update [Lynn's spreadsheet](https://docs.google.com/spreadsheets/d/1NUUN0B1pc6iWxQoTYUW_WE0AwGCMt_qqC-e3CVlG-P0/edit#gid=0)

Hitting a bug on this one: 

![Screen Shot 2021-07-27 at 10 36 23 AM](https://user-images.githubusercontent.com/65608/127173584-0e666b24-40a7-4031-be0f-7dba8fbbb625.png)

**Comment by bess** [comment]
Done!
