### ISSUE TITLE
Import Operations Research and Financial Engineering theses to dataspace prod

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#381]
When completed, don't forget to update [Lynn's spreadsheet](https://docs.google.com/spreadsheets/d/1NUUN0B1pc6iWxQoTYUW_WE0AwGCMt_qqC-e3CVlG-P0/edit#gid=0)

**Comment by bess** [comment]
I am experiencing a bug importing this collection:

![Screen Shot 2021-07-23 at 2 55 11 PM](https://user-images.githubusercontent.com/65608/126828581-089bc07e-fdfd-49a2-9940-05ef62d43715.png)

**Comment by bess** [comment]
I've asked @LynnDurgin for assistance in locating the missing file. From now on, the system will tell us when there is data missing instead of crashing.

**Comment by bess** [comment]
Missing file located, content imported successfully, and from now on we should know more easily when we're missing a file.
