### ISSUE TITLE
Import Princeton School of Public and International Affairs theses to dataspace prod

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#428]
When completed, don't forget to update [Lynn's spreadsheet](https://docs.google.com/spreadsheets/d/1NUUN0B1pc6iWxQoTYUW_WE0AwGCMt_qqC-e3CVlG-P0/edit#gid=0)

Formerly called the "Woodrow Wilson School"

**Comment by bess** [comment]
Done
