### ISSUE TITLE
Publishing a newly imported theses on dataspace-dev results in an error

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#431]
On the newly imported 2021 economics theses, when Lynn tries to publish a work it results in an error. 

![Screen Shot 2021-06-02 at 4 32 19 PM](https://user-images.githubusercontent.com/65608/120652626-f06af780-c44d-11eb-8554-479c23010daa.png)

**Comment by kelynch** [comment]
The DSpace config is not set up with proper EZID credentials for testing ark minting.  

The arks handle minting service in `config/dspace.cfg` should be configured with the following values for dev:

```
handle.prefix = 99999                                                                                                                                                                                                         
ark.ezid_username = $USERNAME                                                                               
ark.ezid_password = $PASSWORD                                                                                           
ark.shoulder = fk4  
```

Test username and password are in LastPass. 

After updating the config, do a `dsrestart` for changes to take immediate effect.
