### ISSUE TITLE
Troubleshoot for Embargo-Lifting for DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#450]
This is necessary in order to restore the automated lifting of embargoes for DataSpace Items.

**Comment by jrgriffiniii** [comment]
It may also be preferred to have an alternative solution for running a report indicating which Items need to have the embargoes manually lifted.

**Comment by jrgriffiniii** [comment]
One should also identify the conditions that leads to the lifting of the embargo, and document why this was originally failing. Additionally, one should see about ensuring that the embargo message need be updated for the JSPUI.

**Comment by kelynch** [comment]
Utilizing the core dspace embargo-lifter command-line tool, I've written a script that executes the command, captures the output, and sends an email to specified parties.

It is in its own repository here: 
https://github.com/pulibrary/dataspace_embargo_lifter

Happy to pair with someone to test this and get it reviewed.

**Comment by kelynch** [comment]
I have scheduled a meeting to pair with Lynn Durgin on this on Tuesday from a user standpoint.  It won't go into production until after the Thanksgiving break.  Is there additional action needed on this ticket, or should we close it?

**Comment by jrgriffiniii** [comment]
Reviewing https://github.com/pulibrary/dataspace_embargo_lifter/blob/main/embargo_lifter.sh, this seems to fully resolve the issue. Thank you very much for creating https://github.com/pulibrary/dataspace_embargo_lifter for this @kelynch!
