### ISSUE TITLE
Is the SrTheses_Approvers group working?

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#456]
We have a problem reported from Lynn Durgin: Some of the senior theses we've been importing are in the wrong workflow step. When this happened during testing we determined that this problem would be caused if the person doing the import did not have the correct permissions. Here is what I am observing on dspace-dev, using a test case of importing 2021 Senior Theses for the African American Studies Department.

1. I follow the instructions here: https://pulibrary.github.io/etd_transformer/process-theses.html
2. The theses are imported but I cannot see them in "My DataSpace." In the past, this has been indicative that they did not import as expected.
3. I investigated the group settings and see that the ability to "add" is configured as "COLLECTION_2666_WORKFLOW_STEP_3"

![Screen Shot 2021-07-09 at 10 38 02 AM](https://user-images.githubusercontent.com/65608/125095223-f59d1100-e0a1-11eb-9a79-3730313f29f3.png)

4. I went to the settings for COLLECTION_2666_WORKFLOW_STEP_3 and I see that it is delegated to a group: "SrTheses_Approvers" and that I am, as expected a member of that group. 
Just to experiment I added myself explicitly as an "EPerson Member" 

![Screen Shot 2021-07-09 at 10 41 28 AM](https://user-images.githubusercontent.com/65608/125095508-40b72400-e0a2-11eb-8829-455f3ab096a3.png)

5. I re-imported the works and this time they are in the correct workflow state. 

![Screen Shot 2021-07-09 at 10 42 43 AM](https://user-images.githubusercontent.com/65608/125095679-6e9c6880-e0a2-11eb-8e09-2f84fbbfd7ae.png)

## Questions:

1. Why do we have the group "COLLECTION_2666_WORKFLOW_STEP_3". Why not just assign directly to "SrTheses_Approvers"? 
2. I tried to re-create this process and it was not repeatable. I removed myself as an individual member of the "COLLECTION_2666_WORKFLOW_STEP_3", deleted all of the works from the 2021 African American Studies Department, re-imported them, and this time they were in the correct workflow state. Is it possible that something within the system is getting cached or otherwise has stale data, and updating the membership refreshes it?

**Comment by kmcelwee** [comment]
I was unable to replicate error, and this problem did not appear in the latest ingest of ~8 departments. I'm under the impression that, since African American Studies is a new major at princeton, this collection's permissions was created after the others in a non-uniform way.  @bess is writing to Atmire.

**Comment by bess** [comment]
Checked with Atmire. They don't know what's happening either. 
We're not able to replicate this, so I'm closing the ticket.
