### ISSUE TITLE
Augment 2021 theses with additional certificate programs

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#462]
Go through this spreadsheet: https://docs.google.com/spreadsheets/d/1bUa16cSRb_Y-kfvbBgKW2-N5PR4wI1eYXihPNobBKvs/edit#gid=933439131

- [x] For each item, open the record in dspace and augment the pu.certificate field with the additional certificate program(s)
- [x] Ask Lynn to take a look when we're done

**Comment by kelynch** [comment]
Raise this issue with the stakeholder (awareness of the highly manual process).
