### ISSUE TITLE
Single Sign-On support for ORCID Identifiers on DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#467]
A question was raised regarding the support for providing single sign-on for users who may not be directly affiliated with Princeton or the PPPL for DataSpace. Might this be something which may be supported using our current integration of Shibboleth?

**Comment by astrochun** [comment]
Sorry, we may have confused the discussion of DataSpace and ORCiD integration. This isn't for having ORCiD  as a sign-on option on DataSpace, but more specifically with the ORCiD SSO login option, which is available at: https://orcid.org/institutional-signin

Princeton University does show up in the list to use NetID for ORCiD login.

Not sure if there's an appropriate GitHub repo for this.
