### ISSUE TITLE
Add Marathi to the list of DataSpace languages

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#472]
This is in response to user request:

```bash
I have a question about DSpace – I recently asked Alpana to upload 2 books in Marathi, 
and she mentioned that Marathi isn’t among the available languages in the dropdown 
menu (though we noticed that Hindi is there). Do we have any control over the 
languages in the dropdown menu for DSpace? Or are those prepopulated?
```

**Comment by jrgriffiniii** [comment]
This is currently blocked by errors which I was encountering when attempting to build the code base for DataSpace and the OAR: https://git.atmire.com/clients/princeton-5/-/commits/oar-TEST-rt4ds-deployment

**Comment by jrgriffiniii** [comment]
I have found that there is a very quick solution for this with the addition of `Marathi` using the following:

https://git.atmire.com/clients/princeton-5/-/blob/dataspace-prod/dspace/config/input-forms.xml#L3041

**Comment by jrgriffiniii** [comment]
This has been temporarily resolved with the following:

![image](https://user-images.githubusercontent.com/1443986/133650368-900ad9d7-db68-497f-8b2f-d113ab6a9464.png)

**Comment by kelynch** [comment]
Would it be simpler for us to include this change in the file at https://git.atmire.com/clients/princeton-5/-/blob/dataspace-prod/dspace/config/input-forms.xml#L3041 properly under source control to consider this completed?

**Comment by jrgriffiniii** [comment]
I can unblock this, and issue a small PR based upon this change.

**Comment by jrgriffiniii** [comment]
https://git.atmire.com/clients/princeton-5/-/commits/dataspace-DEV-lang-marathi-xml-jrg5 tracks these changes for the `dev` environment. I shall issue the merge request very soon for this.

**Comment by jrgriffiniii** [comment]
https://git.atmire.com/clients/princeton-5/-/merge_requests/43 offers this as a draft merge request for the `dev` environment.
