### ISSUE TITLE
Upgrade Symplectic Elements to version 6.5

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#476]
The [Elements server](https://oaworkflow.princeton.edu) is currently running version 5.14; upgrade the software to version 6.4.

We can test this on the [Elements dev server](https://oaworkflow-dev.princeton.edu/) first.

This was previously managed by OIT; see their notes from the dev and prod update process here - https://drive.google.com/drive/folders/14QlPLChkBMVEDnk72f3zdECrzdkJfzuk

**ACCEPTANCE CRITERIA**
- [ ] Do not attempt to get the rest of the team access to the system
- [ ] James should drive and other team members should watch and learn

**Comment by jrgriffiniii** [comment]
Please see my progress within the branch https://github.com/pulibrary/symplectic-elements-utils/compare/upgrading-deployments-jrgriffiniii?expand=1

**Comment by jrgriffiniii** [comment]
This is now currently blocked due to the following error:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/30b8023f-0294-4956-9b9b-f356353e6dc1)

I will be requesting a firewall update in order to restore access to the server.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=sc_req_item&sys_id=19890ec7874cc5909cd197183cbb35e2&view=sp was created for this request.

**Comment by jrgriffiniii** [comment]
When attempting to undertake the upgrade during the maintenance window, the following error arose:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/ff007a3a-eb8d-43c3-b6ed-ca328bfc73b5)

A Symplectic Support ticket which is currently tracking this is https://support.symplectic.co.uk/support/tickets/354904.
