### ISSUE TITLE
Import new faculty HR data into Elements

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#477]
This was previously undertaken by OIT; it was last run in 2019.  No request was made for this in 2020 due to the pandemic; an annual refresh has now been requested again.

Documentation on the process can be found here - https://docs.google.com/document/d/17xWClxhTS3daTUDNKIrjRMMcMB3MhSX6dxKTAhlmDho/edit#heading=h.h8u51h2476b6

**ACCEPTANCE CRITERIA**
- [ ] The latest data has been imported
- [ ] Someone pairs with James on this to observe (even if they don't have the access to drive)
- [ ] We report back to Yuan that this is done

**Comment by jrgriffiniii** [comment]
I have provided some of my own progress with https://github.com/pulibrary/dspace-development/issues/463

**Comment by jrgriffiniii** [comment]
I will need to request confirmation from the users, but this should be resolved.

**Comment by jrgriffiniii** [comment]
This has been resolved during the troubleshooting and resolution for https://app.zenhub.com/workspace/o/pulibrary/dspace-development/issues/510
