### ISSUE TITLE
Does anyone offer symplectic as SAAS? 

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#478]
- [ ] Spend up to four hours researching this & report back to the team

**Comment by kelynch** [comment]
Digital Science is the vendor that provides Symplectic Elements software licenses to customers, and also offers Symplectic as a hosted service.  According to the [vendor website](https://www.symplectic.co.uk/solutions/servicesandsupport/), the service includes: 

* Regular upgrades of Elements software
* Server availability and maintenance 
* Data migrations

Next steps: determine if any workflows are custom workflows that would require something other than what the hosted solution can provide; investigate cost.

**Comment by kelynch** [comment]
The HR People feed feature is core to Elements, non-customized:

* https://support.symplectic.co.uk/support/solutions/articles/6000126041-how-to-install-the-elements-standard-hr-importer

**Comment by kelynch** [comment]
We have clearance to move forward; I am contacting the vendor for a pricing demo and closing this ticket.  Further tickets forthcoming.

**Comment by kelynch** [comment]
Vendor has been contacted, awaiting discussion
