### ISSUE TITLE
Migrate more large datasets to Globus

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#499]
Following up on #261, we'd like to be proactive in getting all of the larger (roughly, >1GB) datasets transitioned over to be available in Globus. PRDS had identified a list of items with @kmcelwee, and we have several folders that are still ready to receive data in Globus. We'll just need to evaluate which of the remaining items are prone to timeout with HTTP downloads and therefore require developer assistance.

**Comment by matthewjchandler** [comment]
Larger files (usually 1.5 GB) timeout when we attempt to download them from the DataSpace front end, so we need someone with direct access to the bitstreams to help us transfer them to the Globus endpoint.

**Comment by hhkitsune** [comment]
Attn: @matthewjchandler 

Link to [spreadsheet](https://docs.google.com/spreadsheets/d/1etA_6llJT_H8F_Pe5UmtyP7cXRlUdiBvEqtIBgrYY2A/edit#gid=0)

Closing ticket, although this will be picked up by individual case. Tickets should be submitted for each dataset to be moved.
