### ISSUE TITLE
Scheduling the synchronization of DataSpace deployment environments (dev, staging, and production)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#513]
I have located some discrepancies between the staging and production environments for Collections between the two deployments (for example, https://dataspace-staging.princeton.edu/handle/88435/dsp0144558h42s does not resolve, whereas https://dataspace.princeton.edu/handle/88435/dsp0144558h42s does successfully resolve).

As I recall, there was discussed some scheme for scheduling the synchronization between the dev, staging, and production environments, but I am afraid that I do not recall whether or not this was implemented by DRDS, or Atmire. If this was not completely implemented, where might this currently stand in terms of prioritization?

**Comment by kelynch** [comment]
Deferring indefinitely.
