### ISSUE TITLE
Resolve access privileges for members of the "Radical Americas" Collection in DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#518]
As reported by the user:

> Then comes four (or five or six) Radical Americas.  I cannot see vol. 1 but [another user can].    For the other 5, when I click on Take Task. Instead of View / Download, my option is  Request a copy.  Nothing happens when I click that.   Actually I just clicked on number 6 and when I released it back to the pool, it no longer appears in my list.  Amy doesn’t see any of these items at all.

**Comment by kelynch** [comment]
I added the reporting user to the review pool for this Collection, and also refreshed the item status by claiming these items' tasks and returning them to the pool so that the reporting user can see and claim them.  I'm waiting to hear back now to see if this resolves their issue.

**Comment by kelynch** [comment]
Confirmed with the user this is resolved; closing.
