### ISSUE TITLE
Remove DataSpace Test Submissions from the user debraski

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#519]

**Comment by kelynch** [comment]
We can do this by aborting the current workflow for the item in the DataSpace admin UI, which will send the back to the submitting user with the option to delete, see screenshot of the DataSpace admin UI:

![Screen Shot 2021-11-04 at 3.57.35 PM.png](https://images.zenhubusercontent.com/5e8212ab97716225cb5a8e50/85c776c4-8c55-4df7-b8ad-1fe4219986a6)

The user can delete a submission by clicking the "Remove" button pictured.

**Comment by kelynch** [comment]
I've emailed the reporting user asking for the titles of the test submissions that need to be removed so I can abort their workflows.

**Comment by kelynch** [comment]
The test items were 3 submitted by me, and 1 submitted by another CaMS staff member.  I've aborted the workflows for all 4, removed the 3 from me, and alerted the CaMS staff member to go in and remove their submission when they have a chance.
