### ISSUE TITLE
Diagnose access privilege errors reported by the DataSpace user account charissaj

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#521]
As reported by the user:

> I am unable to access DataSpace due to a privacy wall. I had previously been able to access it earlier last month. Please help me to resolve this.

> https://dataspace.princeton.edu/handle/88435/dsp01cv43p0846

**Comment by hectorcorrea** [comment]
This might have been the result of an expired certificate. The message displayed to the user might have been misleading. If that is the case we won't be able to replicate it. Ask the user to try again and confirm.

**Comment by kelynch** [comment]
Contacted user to try again; awaiting feedback.

**Comment by kelynch** [comment]
User confirmed access with another browser.
