### ISSUE TITLE
Disable DataSpace Item submission e-mail messages from user accounts steven.knowlton and sahoward

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#525]
As reported by steven.knowlton, there are e-mail messages for Item submissions which should not be sent to these users.

**Comment by jrgriffiniii** [comment]
I suspect that this is somehow related to the e-mail subscription feature described within https://wiki.lyrasis.org/display/DSDOC5x/Email+Subscriptions

**Comment by jrgriffiniii** [comment]
I cannot find any `subscription` records:

```sql
dataspace_prod_db=> SELECT sub.* FROM subscription AS sub;
 subscription_id | eperson_id | collection_id
-----------------+------------+---------------
(0 rows)
```

**Comment by kelynch** [comment]
This appears to have been due to a misconfiguration of group membership in Reviewers in DataSpace.  I think we can close this issue, as group membership has been adjusted.

**Comment by jrgriffiniii** [comment]
https://git.atmire.com/clients/princeton-5/-/blob/dataspace-prod/dspace-api/src/main/java/org/dspace/workflow/WorkflowManager.java#L550 is likely where this is actually being triggered, it appears that there is some group which is receiving messages which should not.

**Comment by jrgriffiniii** [comment]
`periodicals_public` (Group 3975) includes within it the Group `Lib_DigPubs_Submitters` (202), which itself contains two member Groups:

- `Lib_DigPubs_Reviewers` (203)
- `Lib_DigPubs_Approvers` (204)

**Comment by jrgriffiniii** [comment]
`Lib_DigPubs_Submitters` contains the user accounts for Knowlton.

**Comment by jrgriffiniii** [comment]
This has been resolved by @kelynch with a correction made to nested Group memberships.
