### ISSUE TITLE
Abort the Workflow for the DataSpace submission for the user account for khill@

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#527]

**Comment by jrgriffiniii** [comment]
Workflow 44749 was successfully aborted:

```
Delete Workflow: 44749
Are you sure you want to abort this workflow? It will return to the user's personal workspace

Collection: Plasma Science & Technology
Submitter: Kenneth Hill (khill@)
Title: APS DPP 2021 Poster
```

**Comment by astrochun** [comment]
> Workflow 44749 was successfully aborted:
> 
> ```
> Delete Workflow: 44749
> Are you sure you want to abort this workflow? It will return to the user's personal workspace
> 
> Collection: Plasma Science & Technology
> Submitter: Kenneth Hill (khill@)
> Title: APS DPP 2021 Poster
> ```

Thanks. I do not see it in the pool of task. so closing this issue.
