### ISSUE TITLE
Ensure that submission 44763 can be accessed by the user mchandler in their Task Pool

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#543]
The user reported the following:

> We had a DataSpace submission come in that isn't showing up in the task pool for me. I can see it in the workflow list, though: ID 44763; Collection "Physics Research Data Sets"; Submitter cgtully@; Title "Princeton Open Ventilation Monitor". Are you able to manually shift it to the task pool for me? Or perhaps otherwise allow me to preview it?

**Comment by jrgriffiniii** [comment]
> but can you change my permissions on this item so I can view all of the metadata? I'm not getting that button after I accept the task. I'll return it to the pool now

**Comment by jrgriffiniii** [comment]
After attempting to adjust the authorizations, I will need to resubmit this under my own user account.

**Comment by kelynch** [comment]
@jrgriffiniii and I paired on this; I added an "Edit Metadata"/collection approvers group with the affected users and aborted the item's workflow, and James resubmitted the item.  Awaiting confirmation from Matt to see if this worked.

**Comment by kelynch** [comment]
Confirmed fixed by the user, closing.
