### ISSUE TITLE
OAR: Missing Button for Metadata Review

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#562]
## Priority

**Proposed due by:** 1/14/2022, the next time admin (Hannah & Yuan) will meet to work on the workflow.
**Firm due by (to be set by a developer):**

### Description

While in the admin mode, after accepting a task from the pool; the blue button that allows us to edit the metadata for a deposit is not there.

### Acceptance Criteria

- [x] Check that the metadata button is available and working
- [x] Check that the admin (Hannah and/or Yuan) can access the metadata button

**Comment by jrgriffiniii** [comment]
I am currently able to view this button from within the staging environment:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/ddc176d1-d813-41c5-9b70-39874536af20)

While I find that I am a member of all of the following Groups:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/7d67b027-3836-47b9-a97b-2b6678b86d56)

...the user account for `hh4079` is not:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/552ae1e1-41fb-4b22-ac30-226bbacc0bfe)

**Comment by jrgriffiniii** [comment]
While testing the adjustment of Group memberships, I have found that the affected user accounts should now have the proper permissions in the staging and production environments:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/346834df-f452-4e20-9039-a1e6374a5d2d)

I am going to proceed by requesting that the users test this in order to determine whether or not they have the necessary privileges.

**Comment by jrgriffiniii** [comment]
Simply adding the affected users to these Groups did not resolve this for all Items. I will look to try and correctly diagnose this issue.

**Comment by jrgriffiniii** [comment]
There are some differences Group memberships, but these, if anything, should be providing greater (rather than fewer) privileges:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/c8420f14-74ef-484d-a4cb-1009d57a8ccc)

**Comment by jrgriffiniii** [comment]
Further reviewing Group membership, the following Groups do *not* have the affected users as members:

* COLLECTION_102_ADMIN
* COLLECTION_102_SUBMIT
* COLLECTION_102_WORKFLOW_STEP_2
* COLLECTION_103_WORKFLOW_STEP_2
* COLLECTION_103_WORKFLOW_STEP_3
* COLLECTION_104_ADMIN
* COLLECTION_104_SUBMIT
* COLLECTION_34_ADMIN
* COMMUNITY_All_ADMIN
* PU Affiliate

**Comment by jrgriffiniii** [comment]
I have adjusted the membership for these Groups, and requested that the affected users test the feature within the production environment.

**Comment by jrgriffiniii** [comment]
Unfortunately, this also did not resolve the errors. Further, the privileges must now be further adjusted, as the following was reported:

> I'm not sure if this is related, but the labels in our pool are showing new labelling that shouldn't be there. Our labels should only be "needs review" or "review".

**Comment by jrgriffiniii** [comment]
`org.dspace.workflow.WorkflowManager` contains the functionality for managing the workflow state of the `WorkflowItem`, and currently one of the affected Items lies within the state of `WFSTATE_STEP2POOL` (value of `state` 3). This has the following description:

```
public static final int WFSTATE_STEP1 = 2; // task - reviewer has claimed it
public static final int WFSTATE_STEP2POOL = 3; // waiting for an admin to
                                                   // claim it
public static final int WFSTATE_STEP2 = 4; // task - admin has claimed item
```

As this WorkflowItem *does* have an owner, this might be a case in which the state was erroneously set to 2.

**Comment by jrgriffiniii** [comment]
Following a Zoom meeting with Hannah and Yuan yesterday afternoon, a number of details were identified regarding this issue, and the following steps were identified as needed to resolve this:

- Remove the `Accept/Reject/Edit Metadata Step` workflow from all Collections
- Remove the `Edit Metadata Step` from all Collections
- Create the `Accept/Reject Step` for all Collections

In response to Yuan informing me that a user, following the testing of this, was receiving e-mails, I have also created a `Submitters` workflow for all Collections, and I have migrated any existing users from the `Accept/Reject/Edit Metadata Step` into the `Accept/Reject Step` workflow.

**Comment by jrgriffiniii** [comment]
I have requested user review for these changes, and will proceed based upon their feedback.

**Comment by jrgriffiniii** [comment]
There were some additional synchronization issues which arose which required the following:

```sql
update workflowitem set state=3 from (select w.item_id from metadatavalue as v inner join workflowitem as w on v.resource_id=w.item_id  where v.text_value like '%Final published version.%' and w.state=3) as subquery where workflowitem.item_id=subquery.item_id;
```

**Comment by jrgriffiniii** [comment]
I am finding the following in response to a database query:

```sql
select workflow_id,item_id,collection_id,state,owner from workflowitem where state=1;
 workflow_id | item_id | collection_id | state | owner
-------------+---------+---------------+-------+-------
        2663 |    2763 |            51 |     1 |
        1476 |    1578 |            46 |     1 |
```

**Comment by hhkitsune** [comment]
@jrgriffiniii I'm sorry to report we are experiencing new issues with the task labels that may be related to this and issue #559.

The labels in the task pool are currently incorrectly assigned. Please see ht image which shows many of the task pool records as "reviewed" and many of these are not yet in the review stage. Only the records with the metadata for "version" have been reviewed. I'm available to Zoom if you would like a walk-thru for what we are experiencing.
<img width="1440" alt="Screen Shot 2022-01-14 at 3 46 18 PM" src="https://user-images.githubusercontent.com/50670293/149583023-8d7c6fd4-d8dd-4f69-bb23-f5c5dad4f51f.png">

**Comment by jrgriffiniii** [comment]
Reviewing the database records for these, I find the following:

```
oar_prod_db=> select count( workflow_id ) from workflowitem where state=6;
 count
-------
     1
(1 row)

oar_prod_db=> select count( workflow_id ) from workflowitem where state=5;
 count
-------
  1628
(1 row)


oar_prod_db=> select count( workflow_id ) from workflowitem where state=4;
 count
-------
    15
(1 row)

oar_prod_db=> select count( workflow_id ) from workflowitem where state=3;
 count
-------
   478
(1 row)

oar_prod_db=> select count( workflow_id ) from workflowitem where state=2;
 count
-------
     0
(1 row)

oar_prod_db=> select count( workflow_id ) from workflowitem where state=1;
 count
-------
     2
(1 row)
```

Investigating the `owner` field, I have found the following:

- Records in state 1 do not have owners
- Records in state 2 are not in the system
- Records in state 3 do not have owners
- Records in state 4 have owners for all records
- Records in state 5 do not have owners
- Records in state 6 have owners for all records

**Comment by jrgriffiniii** [comment]
Evaluating the code base, it appears that, for past releases from Elements to the OAR, the Items were placed within workflow state 2. They are, instead, now placed within workflow state 1.

Hence, all Items within workflow state 1 should be placed within workflow state 2.

**Comment by jrgriffiniii** [comment]
Following several further attempts at testing, the following workflow configuration was needed to support the desired behavior:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/754911d7-ed91-47d9-b6c6-3cbc162bf653)

**Comment by jrgriffiniii** [comment]
These Workflows have been manually updated for all Collections.

**Comment by jrgriffiniii** [comment]
The button is now being rendered for my user account:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/425987ee-9542-42e7-ad4c-f9af8b2b56d4)

**Comment by jrgriffiniii** [comment]
This should be considered resolved until I receive feedback indicating otherwise.
