### ISSUE TITLE
Symplectic Elements: Missing Results for Specific Query

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#564]
## Priority

**Proposed due by:** 1/14/2022, the next time admin (Hannah & Yuan) will meet to work on the workflow.
**Firm due by (to be set by a developer):**

### Description

While in Admin mode, the query for "Publications in OA Policy" is only showing 27 results. We expect the correct number to be around 4000-5000 records.

Note: The "Publications in OA Policy" query is located under the "Research Admin" tab.

### Acceptance Criteria

- [ ] Results for "Publications in OA Policy" should number ~4000
- [ ] Please check that Yuan and Hannah can see the correct results

**Comment by hhkitsune** [comment]
Here is a screenshot showing the current query results of 27 records:

![Screen Shot 2022-01-12 at 4 06 32 PM](https://user-images.githubusercontent.com/50670293/149223351-9af94d74-c3b7-4d48-8968-6c3092d7613e.jpeg)

**Comment by jrgriffiniii** [comment]
After reviewing the `Data source management` interface form, the synchronization seems to be inactive:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/277ef171-aef3-434e-9920-93481866fc47)

**Comment by jrgriffiniii** [comment]
Further information was provided within the server logs with the following:

```bash
Log entry ID: 21bb7be5-9cb0-4cc1-8f35-ef9bff557be9
Logged at: 15:19:28.023 26/01/22

Level 1:
-------
Exception type: System.ServiceModel.EndpointNotFoundException
Message: There was no endpoint listening at net.pipe://localhost/elements-default/synchroniser that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
Stack trace:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage, IMessage)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&, Int32)
at Symplectic.Elements.Sync.ApiClient.ISynchroniserApi.GetState()
at Symplectic.Elements.Sync.ApiClient.SynchroniserClient.GetState() in elements\Sync.ApiClient\SynchroniserClient.cs:line 33, char 4
at Symplectic.Elements.Website.Application.ErrorLoggingSynchroniserClient.GetState() in elements\Website.Application\ErrorLoggingSynchroniserClient.cs:line 43, char 5

Level 2:
-------
Exception type: System.IO.PipeException
Message: The pipe endpoint 'net.pipe://localhost/elements-default/synchroniser' could not be found on your local machine. 
Exception not yet thrown.
```

**Comment by jrgriffiniii** [comment]
Manually executing the `Run` operation for the `Synchroniser` background service (this lies within the `Scheduled Jobs` interface form) led to the successful resynchronization of the data sources:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/65d86777-d0e7-485e-9b45-dd1f5aee4cbf)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/00803a9d-2d8c-4cbf-9764-e07751273d5e)

This was likely related to the Elements Scheduler system process not being running (please see #572)

**Comment by jrgriffiniii** [comment]
This seems to still be requiring some time to reindex:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/8d05d5e3-ce44-4dd3-bac9-078e94e5aa52)

**Comment by jrgriffiniii** [comment]
As I cannot seem to advance this much further without incurring additional possible delays, I have created a support request with Symplectic: https://support.symplectic.co.uk/support/tickets/366105

**Comment by jrgriffiniii** [comment]
My diagnosis is that, assessing the logs for the search index rebuild jobs, that this *should* be rebuilding on a weekly basis, but that this is somehow failing to rebuild. As a result, the last successful rebuild seems to have taken place during November 2021.

Unfortunately, I cannot locate in the service log entries where this failure might originate. Please be aware that I have also investigated the IIS service logs within the Windows Server environment.

**Comment by jrgriffiniii** [comment]
The support specialist from Symplectic has requested the logs from the server in order to diagnose the issue. I shall proceed by providing these.

**Comment by jrgriffiniii** [comment]
Attempting to retrieve the logs from Symplectic yields the following:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/dddc4eaa-cfff-4c1a-bc61-e1e91ecca4c2)

**Comment by jrgriffiniii** [comment]
After refining the search to a more restricted date range, I was able to successfully provide the logs to Elements. Additionally, the support specialist also provided guidance as to where I may find server-side logs, and I provided some small set of these. Their response was the following:

```bash
Thanks for these. Looking at the System Log, the first thing I want to check on is whether you know why the website application is being started and shut down every day -- or, at least, every day in the logs you sent. 
​
I'm beginning to wonder if the re-indexer won't complete because it's already running when you ask it to re-index. I recall seeing something like that a few years ago, but you've got a pretty old version of Elements. The solution might be going into the directory and manually deleting the Search.Index, then letting it rebuild from scratch, but I hesitate to recommend something that drastic without consulting with a Dev. Unfortunately, it's too late in the day for me to get help from anyone in London, so I'm afraid we'll need to wait for Monday.
```

Hence I will delay addressing this until Monday.

**Comment by jrgriffiniii** [comment]
The following `kernel` events were logged for the server within the frame of time for the last indexing request:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/af340376-b2cb-4d8f-9b1e-d4c304fea5eb)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/8e80a80d-3fb1-462d-89f0-cb4f194d7718)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/0adaf624-ab13-4bf8-9d8b-d7c937d4c07f)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/13c8c80a-cbc4-4817-93aa-0ae7b4cc8913)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/4c0413f9-bc6c-4e81-b18e-2516ff44fd74)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/f2aac1d2-b6aa-4ef4-9b56-740a53f8e702)

**Comment by jrgriffiniii** [comment]
The following entries with the `Application` log seem to also indicate that the `RestartManager` is being activated on a regular basis:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/f8eabf89-3025-4a62-9b24-03343ab5c973)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/116d4e82-373e-4cd3-894a-7e519b36642d)

**Comment by jrgriffiniii** [comment]
Following an initial review, the reporting users have confirmed that this seems to be resolved. Should other errors be discovered, I shall proceed with reopening this.
