### ISSUE TITLE
Create a PPPL Group that permits submission to all PPPL collections

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-development#566]
Per recent discussions, and a request from a PPPL researcher (Menard), a group that is added to all PPPL collections is desired. This would provide greater flexibility for users that work across multiple projects.

Action items are:
- [x] Create the group
- [x] Add the group to all PPPL Collections
- [ ] Test to ensure that the group works as intended

**Comment by astrochun** [comment]
Group no: 3866 (dev), and XXX (prod)

**Comment by astrochun** [comment]
@matthewjchandler, the PPPL-AllCollections-Submitters was created (includes myself, Aileen, and Jon) and has been added to the Submission list for all PPPL Collections. Not sure what's the best way to test this given that the PACM group is added to submission for all of these collections.

**Comment by matthewjchandler** [comment]
Thanks @astrochun! I don't mind waiting to test until we have another real use-case. I don't foresee a high-consequence scenario for this group not working.

**Comment by astrochun** [comment]
Sounds good. I'll close this issue for now and we can revisit when there's a need.
