### ISSUE TITLE
OAR: Missing Steps in Task Pool Workflow

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#567]
## Priority

**Proposed due date:** 1/21/2022, the next time admin (Hannah & Yuan) will meet to work on the workflow.

**Reason:** Our workflow is halted because of this issue.
**Note:** This issue may be related to issues [559](https://github.com/pulibrary/dspace-development/issues/559) and [562](https://github.com/pulibrary/dspace-development/issues/562)

**Firm due by (to be set by a developer):**

### Description

**This issue regards problems in the taskpool:** 

Items are being published directly to the OAR after the metadata review is completed. For reference, the workflow steps are supposed to be:

1. A student worker selects an item from those in the taskpool with the "needs review" label
2. After accepting the task, a student worker uses the metadata button (see issue [562](https://github.com/pulibrary/dspace-development/issues/562)) to review and edit the record level metadata for the item
3. Upon completion of step two, the task is then returned to the taskpool and the label changes to "reviewed"
4. An administrator then accepts a "reviewed" task and uses the "committed to archive" button to publish to the OAR

Currently, items are being published directly to the OAR after the metadata review is completed in step two. Steps three and four of our workflow are missing.

### Acceptance Criteria

**Note:** completion will require testing with Yuan and Hannah

- [ ] After step two, check that items are always returned to the taskpool with the label "reviewed"
- [ ] Make sure items in the taskpool with the label "reviewed" have the "committed to archive" button available for administrators to publish to OAR

**Comment by jrgriffiniii** [comment]
This is closely related to, and will be resolved by the solutions introducted for #562

**Comment by jrgriffiniii** [comment]
This should be considered resolved until I receive feedback indicating otherwise.
