### ISSUE TITLE
Redirect for mudd.princeton.edu

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#569]
Some ETDs (e.g., https://dataspace.princeton.edu/handle/88435/dsp015999n348d) contain a hard coded link to a defunct web address: mudd.princeton.edu. This URL should redirect to https://library.princeton.edu/special-collections/mudd. 

**ACCEPTANCE CRITERIA**
- [ ] If I enter mudd.princeton.edu I am redirected to https://library.princeton.edu/special-collections/mudd

**Comment by kayiwa** [comment]
ran nginxplus playbook and transferred name to loadbalancer.
