### ISSUE TITLE
Import dissertations MARC records for November 2020 into DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#575]

**Comment by jrgriffiniii** [comment]
This is awaiting a response from an e-mail message sent to Lynn Durgin this morning today at 10:14 EST.

**Comment by jrgriffiniii** [comment]
Please find the screenshot here:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/e53e619f-429f-409d-b223-b5ac9abeef89)

**Comment by jrgriffiniii** [comment]
It was clarified that the November 2020 MARC records need to be delivered to RDSS.

**Comment by bess** [comment]
Bess will send follow up email.

**Comment by bess** [comment]
Lynn verifies that there are no dissertations actually missing. Closing this ticket.
