### ISSUE TITLE
Update the InCommon SSL certificate for oar.princeton.edu

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#576]
The following alert was received for the `oar.princeton.edu` domain name:

```bash
Your InCommon SSL certificate for oar.princeton.edu will expire soon. Date and time of expiration: 03/03/2022 23:59 GMT.
```

**Comment by bess** [comment]
We no longer the the InCommon SSL cert. The cert will update automatically via Let's Encrypt. This is running on google cloud.

**Comment by jrgriffiniii** [comment]
As this was not provided, I will update this manually for the server environment.

**Comment by kelynch** [comment]
Operations is looking into this.

**Comment by jrgriffiniii** [comment]
This was successfully resolved with updates made to `letsencrypt`, thank you very much @kayiwa!

![image](https://user-images.githubusercontent.com/1443986/161617614-b192e9ba-6648-4399-8ae8-184cc059aff4.png)
