### ISSUE TITLE
DataSpace: Data for Matt Chandler

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#602]
## Due Dates

**Proposed Due Date:** Please complete by March 4, 2022

Reason: This has been pending for some time and we would like to see it completed.

**Adjusted Due Date:**

Reason:

## Description:

This is the "data dump" discussed in our meetings. Please place the data into the folder that Kate has prepared.

## Acceptance Criteria:

- [ ] Check with Matt Chandler to see that the data has been received.

**Comment by bess** [comment]
I used this command to export the data: 
`pg_dump -U dataspace_prod_db_user -d dataspace_prod_db -f 21Feb2022_full_dataspace_dump.sql`

The resulting sql dump file is now on my local laptop. @kelynch let me know when you have time to set up S3 access with me.

**Comment by kelynch** [comment]
Matt will be available starting the week of 2022/02/28 to test this; closing this issue now.
