### ISSUE TITLE
Ability to identify sub-communities in the curation stage

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-development#603]
## Due Dates

**Proposed Due Date:** First week of March 2022

Reason:

This continues to be an issue that limits curation

**Adjusted Due Date:**

Reason:

## Description:

PPPL has collections within sub-communities. When a submitter selects a collection in one of these sub-communities, it's unclear the hierarchy and thus where the dataset will be published under. Three of these PPPL collections are named "PPPL Collaborations". The email notifications, as well as, the "Content > [Item/Workflow]" tools does not provide such hierarchy.

We have dealt with this for a number of deposits. The submitter selects the wrong collection. Time passes. We don't know if we fixed the issue. Back/forth emails continue with workflow being aborted.

## Acceptance Criteria:

- [ ] I really don't care how, but an admin/curator should be able to see the community > sub-community hierarchy. Ideally, this should be included in email notifications.

**Comment by kelynch** [comment]
Superseded by PDC Describe and Discovery
