### ISSUE TITLE
Request an OIT Service Account for granting the Digital Science Team access to Symplectic Elements Servers

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#615]
This would a shared OIT Service Account for the following Windows Servers:

- cisdr201w (oaworkflow.princeton.edu)
- cisdr301w (oaworkflow-dev.princeton.edu)

Further, it would be necessary to ensure that the service account have administrative access to both Windows Server environments.

## Acceptance criteria
- [x] Sponsored account for vendor created 
- [x] Service account associated with sponsored account created 
- [x] Access to the above servers requested through OIT
- [x] Access granted by OIT 
- [ ] Access confirmed by vendor

**Comment by kelynch** [comment]
This account has been requested and created.  I will now put in a separate service request for it to have full admin access to the above servers.

**Comment by kelynch** [comment]
Access has been requested, request number RITM0358143.

**Comment by kelynch** [comment]
Access granted by OIT this morning; asking the vendor to test and confirm access.

**Comment by jrgriffiniii** [comment]
In order to access either server environments, one will first need to access the bastion host `lib200w.princeton.edu`. This must be undertaken using the Microsoft Remote Desktop client:

# macOS
- https://apps.apple.com/us/app/microsoft-remote-desktop/id1295203466?mt=12
# Windows
- https://support.microsoft.com/en-us/windows/how-to-use-remote-desktop-5fe128d5-8fb1-7a23-3b8a-41e636865e8c
# *NIX
- https://github.com/TigerVNC/tigervnc

**Comment by jrgriffiniii** [comment]
Please be aware that one must be authenticated on the Princeton VPN (https://princeton.service-now.com/service?id=kb_article&sys_id=KB0012373), and that one must ensure that the OIT has explicitly provided authentication privileges for the service account on the bastion host.

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/now/workspace/agent/record/incident/df2613eb8766811012ae43bd0ebb35f0/params/selected-tab-index/3/sub/record/sc_task/de2d17ab87668110d1c6c8cd0ebb35cc tracks the request for VPN access for `dslica` (this was completed).

https://princeton.service-now.com/now/workspace/agent/record/incident/df2613eb8766811012ae43bd0ebb35f0/params/selected-tab-index/3/sub/record/sc_task/64be6b2b876a8110d1c6c8cd0ebb3508 tracks the progress of the request to ensure that `dslica` can authenticate for `lib200w` (this is still in progress)

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/now/workspace/agent/record/incident/df2613eb8766811012ae43bd0ebb35f0/params/selected-tab-index/3/sub/record/sc_task/64be6b2b876a8110d1c6c8cd0ebb3508/params/selected-tab-index/0 was marked as complete. I am going to proceed by enquiring that Digital Science attempt to test authenticating on `lib200w.princeton.edu`.

**Comment by jrgriffiniii** [comment]
The vendor has confirmed access with the following message:

> Thu 4/14/2022 12:14 PM
> Hi all,
> 
> I managed to remote to both CISDR201W and CISDR301W.
> The main concern that I have right now is the version Elements is on your systems : v5.14.
> I'll have a chat with the team and get back to you after we figure out what would be the less painful solution for this migration.

The exchanges following this message did not indicate that this access was insufficient for the vendor to proceed.
