### ISSUE TITLE
OA Waiver DB: Please provide Hannah H with admin access

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#626]
## Due Dates

**Proposed Due Date:** Soon as possible, though not on fire.

Reason: I am the point person to write user issues for this product or to check development work on behalf of users, so will need admin access to the database. Please address this issue when you have a free moment.

**Adjusted Due Date:**

Reason:

## Description:

Please provide Hannah Hadley with admin access (the same level as Yuan Li) for this product.

## Acceptance Criteria:

- [ ] Hannah will have the same access to this product as Yuan Li
- [ ] Please check with Hannah to confirm she has this level of access

**Comment by jrgriffiniii** [comment]
This should be updated for the `production` environment. Thank you for your patience @hhkitsune!
