### ISSUE TITLE
Symplectic Elements: "Claimed" Items Missing in Queue

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#627]
## Due Dates

**Proposed Due Date:** 4/8/22

Reason: This impacts an aspect of our workflow.

**Adjusted Due Date:**

Reason:

## Description:

(Note: Hannah demonstrated this issue for James in a meeting)

The following steps from our workflow will describe the issue experienced:

- We begin by impersonating a researcher; "claim or reject" is selected under "My actions" section
- Opening "My actions" will default to the "Pending tab" which is where we may select or reject records
- After validating a record is accurate, we may choose the "Claim as Mine" button
- This claims the item and it will now show under the "Mine" tab 
- Next, go to the tabs at the top of the page and select "Research Admin"
- Select "Publications in OA Policy" and narrow the search to the title that was claimed
- Our issue is that the claimed title currently doesn't show in this list 

## Acceptance Criteria:

- [ ] Claimed items will show in the "Publications in OA Policy" queue
- [ ] Please check with Hannah or Yuan to confirm the issue is fixed

**Please reach out to Hannah if you have any questions**
  
## After validating a record is accurate, we may choose the "Claim as Mine" button

![Screen Shot 2022-03-31 at 3 34 08 PM](https://user-images.githubusercontent.com/50670293/161137823-d215560c-8fa2-4500-b793-430c7d77d3ce.jpeg)

## Select "Publications in OA Policy" and narrow the search to the title that was claimed

![Screen Shot 2022-03-31 at 3 35 35 PM](https://user-images.githubusercontent.com/50670293/161137840-95fd8235-0013-40ba-a006-8bc93ed105fa.jpeg)

## Our issue is that the claimed title currently doesn't show in this list 

![Screen Shot 2022-03-31 at 3 35 27 PM](https://user-images.githubusercontent.com/50670293/161137862-454fff0b-9f50-4113-b7db-89215b27cb73.jpeg)

**Comment by jrgriffiniii** [comment]
Directly querying the MSSQL Server database is necessary in order to begin diagnosing this:

```mssql
USE elements;

GO
SELECT * FROM dbo.OBJECT_tblObject WHERE ID=173746;
GO
```

**Comment by jrgriffiniii** [comment]
Comparing a single claimed and a single unclaimed publication, there only seems to be a difference in the `EverApproved` field:

![image](https://user-images.githubusercontent.com/1443986/161274510-5993213e-e3f5-45b7-801f-11465a0e61aa.png)

**Comment by jrgriffiniii** [comment]
For reference, those records with a non-NULL `User_ID` field persist attributes for users within the application.

**Comment by jrgriffiniii** [comment]
Currently, as my own user, I cannot search for any recommended publications which have not been claimed at all:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/9de894ef-122f-4daf-bdae-1302178f27ea)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/dccbb427-5bbe-4e33-b835-339d885e9aa1)

**Comment by jrgriffiniii** [comment]
Searching for publications and linking my user account to one did not seem to prevent users from being able to search for the record by title:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/cfd5357d-916b-4e09-a897-29c21adf275b)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/c46f5532-8e53-416b-9d27-ef3b157b1d93)

**Comment by jrgriffiniii** [comment]
Inspecting the database records, the one distinguishing factor is the difference in modification dates:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/371f5762-20d1-43e8-9764-4433fd867c88)

This would coincide with a date earlier than that of the last search index regeneration:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/66bd3313-c2f5-4222-8b0a-8f904abbea10)

**Comment by jrgriffiniii** [comment]
I am going to proceed by attempting to generate the search index for today.

**Comment by jrgriffiniii** [comment]
This seems to be completely resolved, and as the previous index regeneration jobs are completed, the user interface updates are now at a normal speed:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/cd3df0df-c24d-4e45-bf1c-5e60ba0ad88b)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/fdeaedf9-d96e-47ec-8832-3d3795f254f5)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/a6e195d9-b93e-41e0-a9f4-7aa1d8161ca1)

**Comment by hhkitsune** [comment]
We are still experiencing the issue. Please see the images below.

## Yuan is impersonating the researcher and has claimed the publication circled in red. It now shows under the "mine" tab, which you can see in the image.

![image (6)](https://user-images.githubusercontent.com/50670293/168873337-ef2f1d98-1b63-4942-ad10-20a28c616fc7.png)

## Yuan then goes to look for this under "Publications in OA Policy" using the author's name.

![image (7)](https://user-images.githubusercontent.com/50670293/168873368-4d5d9131-6487-471b-8ed2-68006a10dda4.png)

## Yuan cannot find the article she had claimed in the list of publications.

![image (8)](https://user-images.githubusercontent.com/50670293/168873379-b0a8054e-33ad-4a83-be17-ad14fa531c62.png)

**Comment by jrgriffiniii** [comment]
The Windows Server seems to have been restarted or crashed following the closing of this issue:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/154d6098-3f46-4b04-a247-ae8cca7f66ba)

**Comment by jrgriffiniii** [comment]
In order to try and advance this, I am going to attempt to manually rebuild the search index given the service outage earlier today:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/a6b34b19-eefd-4040-865b-f4aa53106890)

**Comment by jrgriffiniii** [comment]
Reindexing seems to be functioning as expected on a daily basis within the production environment:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/6297ea09-58d0-49c9-84ee-892523e5f420)

**Comment by jrgriffiniii** [comment]
The migration was successfully completed.
