### ISSUE TITLE
Incorrect column names in the E-people during search

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-development#631]
## Due Dates

**Proposed Due Date:** Not critical

Reason:

**Adjusted Due Date:**

Reason:

## Description:

Please be concise

I was using DataSpace E-people pop-up and noticed that when one conducts a search, the field heading changed such that the "First Name" is now "Last Name". This was rather confusing. See screenshots below.

## Acceptance Criteria:

- [ ] The second Last Name column needs to be First Name

![Screen Shot 2022-04-27 at 1 57 56 PM](https://user-images.githubusercontent.com/20305734/165630205-89fe5728-3e6e-4c8c-93f9-14865aee05e8.png)

**Comment by kelynch** [comment]
Superseded by PDC Describe and Discovery
