### ISSUE TITLE
Enhance dissertation MARC data with arks

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#634]
Per email message from Lynn Durgin, augment November 2020, January 2021, and April 2021 dissertation MARC with arks from DataSpace, then send to DACS for loading into Alma.

These batches still have bound copies associated with them; this is likely the last batch of this nature.

Files here - [FW__MARC_records_for_PU_dissertations.zip](https://github.com/pulibrary/dspace-development/files/8710886/FW__MARC_records_for_PU_dissertations.zip)

**Comment by jrgriffiniii** [comment]
These have been imported and indexed into Alma and Orangelight:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/97854659-42df-4710-9ebe-af60db2165fd)

**Comment by jrgriffiniii** [comment]
A reimport has been scheduled for the batches, and the estimated delivery time is for the end of next week.

**Comment by jrgriffiniii** [comment]
I failed to confirm that this was resolved, but I shall do so, and then close this.
