### ISSUE TITLE
Update GlobalProtect VPN range for IP-restricted items

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#635]
Ensure that GlobalProtect VPN IP ranges (https://princeton.service-now.com/service?id=kb_article&sys_id=KB0012390) are reflected accurately in the `authentication-ips.cfg` file in `config/modules` to allow access to IP-restricted items, for example: 

https://dataspace.princeton.edu/handle/88435/dsp01qn59q708j

If on campus or accessing over VPN, there should be a blue view/download button at the bottom, replacing the green request button.

This was reported as no longer functioning on 2022/05/27

**Comment by jrgriffiniii** [comment]
Resolved by the following:

- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/13
- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/12
- https://github.com/PrincetonUniversityLibrary/princeton-5/pull/11

**Comment by jrgriffiniii** [comment]
This was reported as blocking campus IP addresses by a colleague within Public Services

**Comment by jrgriffiniii** [comment]
Another user has reported that this is still not fixed. I am now attempting to port the IP addresses directly from https://princeton.service-now.com/service?id=kb_article&sys_id=b9e0c08b1b967784aaf7217e6e4bcb7b

**Comment by jrgriffiniii** [comment]
I don't believe that this was properly resolved from within the code base. I would like to please take the time to review this before closing this (or, if preferred, create a separate Issue).

**Comment by jrgriffiniii** [comment]
This was indeed resolved.
