### ISSUE TITLE
OAR: Remove Test Article

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#679]
## Priority

**Kind of warm, but not very warm or on fire.**

## Description:

Please remove the test article from the recent submissions feature.

## Image shows test article is showing under the recent submissions feature

![Screen Shot 2022-10-04 at 3 43 27 PM](https://user-images.githubusercontent.com/50670293/193911900-f8b251b9-478b-407f-8d23-20cc60bf3c18.jpeg)

## Acceptance Criteria:
- [x] The test article is no longer visible under the recent submissions feature
- [x] Please remember to laugh : )

**Comment by jrgriffiniii** [comment]
I am very sorry for this, the Item has been deleted. However, while trying to also address test Workflow Items, these seem not to be able to be deleted. I can look to scope this for another GitHub Issue. Thank you for your continued patience.
