### ISSUE TITLE
Insert ARKs into DataSpace records for May 2021, September 2021, November 2021 and January 2022

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#683]

**Comment by jrgriffiniii** [comment]
The batches from May 2021 and September 2021 have been cleaned in https://github.com/jrgriffiniii/dataspace-proquest-marc/tree/october-2022-batch

**Comment by jrgriffiniii** [comment]
The November 2021/January 2022 batch has been cleaned in https://github.com/jrgriffiniii/dataspace-proquest-marc/tree/october-2022-batch

**Comment by kelynch** [comment]
This list has been transferred to CaMS team for further data loading.
