### ISSUE TITLE
Change template for new collections

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#684]
New collections were created by staff request as follows:

* Serials and series reports (Access Limited to Princeton) - Boletín de estadísticas vitales - https://dataspace.princeton.edu/handle/88435/dsp016682x717m
* Serials and series reports (Access Limited to Princeton) - Intermedia - https://dataspace.princeton.edu/handle/88435/dsp019z903308m
* Serials and series reports (Access Limited to Princeton) - SAMLA news - https://dataspace.princeton.edu/handle/88435/dsp01fq977z00c
* Serials and series reports (Access Limited to Princeton) - SAMLA conference - https://dataspace.princeton.edu/handle/88435/dsp01kh04ds91h
* Serials and series reports (Access Limited to Princeton) - The Funambulist - https://dataspace.princeton.edu/handle/88435/dsp01q524jr99h
* Serials and series reports (Access Limited to Princeton) - Newsletter of the Society of Wood Engravers - https://dataspace.princeton.edu/handle/88435/dsp01tx31qm91q
* Serials and series reports (Access Limited to Princeton) - Bomb - https://dataspace.princeton.edu/handle/88435/dsp01zp38wg84m
* Serials and series reports (Access Limited to Princeton) - The national interest - https://dataspace.princeton.edu/handle/88435/dsp01zg64tq14z

However, the template for the submission forms does not appear to match expectations, see staff follow-up email below:

> I see the submission form below for these new collections and I don’t see the field “Serial/Series Title, Year, Volume, Number” on this form. It looks like this form is for monographic reports instead of serials and series reports. We use the Series/series reports collection template (see below) for serials and series reports.

**Comment by jrgriffiniii** [comment]
This likely is related to a set of XML configuration files which must be updated for the form fields.

**Comment by jrgriffiniii** [comment]
This requires `staging` and `dev` PRs also.

**Comment by jrgriffiniii** [comment]
This has been resolved following reviews and merging of pull requests by @bess (thank you very much again!)
