### ISSUE TITLE
Request to have members of Digital Science receive a monthly export of the HR feed required for Elements

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#707]
As members of Digital Science have a dedicated OIT service account (`dslica`), perhaps this might be available to be used as an e-mail account which receives the HR import feed for Elements directly from the Office of Information Technology.

This currently requires that https://support.symplectic.co.uk/support/tickets/421535 confirm that the current structure of the data does not block it from being imported into Elements.

**Comment by jrgriffiniii** [comment]
Until #702 has been tested, I am not quite certain of the format required by Digital Science. Hence, I am going to consider this blocked.

**Comment by jrgriffiniii** [comment]
This is now being tracked with the following SN@P ticket: https://princeton.service-now.com/now/workspace/agent/record/incident/2f8cdc748745615818ce52883cbb358d

**Comment by jrgriffiniii** [comment]
This has been advanced beyond the SN@P ticket, as the parties involved in configuring the Cognos reports which generate the report for the existing Samba/CIFS file share are in direct communication with me using e-mail messages.

**Comment by jrgriffiniii** [comment]
This has been last updated on 02/17/23, but is still marked as `In Progress`:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/9111c712-60eb-4cdd-85d8-afd3a3426725)

**Comment by jrgriffiniii** [comment]
While the e-mail messages are currently being sent to the requested e-mail addresses, the links themselves resolve to assets within the Princeton Data Warehouse which either do not exist, or to which I do not currently have access.

Colleagues within OIT were notified of this, and this is still actively being diagnosed.

**Comment by jrgriffiniii** [comment]
I have not been receiving this e-mail on a weekly basis (as I was). I will look to reopen this on SN@P.

**Comment by jrgriffiniii** [comment]
This is being actively advanced using a new SN@P ticket, https://princeton.service-now.com/now/workspace/agent/record/incident/8b148fe4873de954731f322d0ebb3583

**Comment by kelynch** [comment]
Creating a new ticket for remaining tasks with OIT, closing this one.
