### ISSUE TITLE
OAR/DSpace: Incorrect counts for Collections

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#710]
## Description:

The [Departmental Collections page](https://oar.princeton.edu/collection-list) is showing incorrect counts for some of the collections. For example, Art & Archaeology is showing "0" but there are "26" items when you click the collection link and go to that collection's page.

Here is a list of the collections that need to be fixed:
- African American Studies (shows 1, but has 29)
- Art & Archaeology (shows 0, but has 26)
- Astrophysical Sciences (shows 466, but has 779)
- Chemical & Biological Engineering (shows 130, but has 287)
- Chemistry (shows 48, but has 443)
- Civil And Environmental Engineering (shows 93, but has 97)
- Comparative Literature (shows 0, but has 19)
- Computer Science (shows 185, but has 1069)
- East Asian Studies (shows 21, but has 22)
- Ecology and Evolutionary Biology (shows 393, but has 420)
- Electrical Engineering (shows 87, but has 320)
- English (shows 0, but has 21)
- Faculty Publications (School of Public and International Affairs) (shows 0, but has 619)
- Geosciences (Shows 0, but has 476)
- German (Shows 0, but has 1)
- History (shows 0, but has 64)
- Journal of Public and International Affairs (shows 0, but has 1)
- Library (shows 0, but has 3)
- Liechtenstein Institute on Self-Determination (shows 0, but has 58)
- Mathematics (shows 296, but has 297)
- Mechanical and Aerospace Engineering (shows 76, but has 289)
- Molecular Biology (shows 318, but has 564)
- Music (shows 0, but has 3)
- Near Eastern Studies (shows 0, but has 23)
- Operations Research and Financial Engineering (shows 144, but has 312)
- Philosophy (shows 1, but has 20)
- Physics (shows 1102, but has 1339)
- Politics (shows 64, but has 69)
- Program in Gender and Sexuality Studies (shows 0, but has 2)
- Psychology (shows 250, but has 251)
- Religion (shows 0, but has 36)
- School of Public and International Affairs (shows 620, but has 682)
- Sociology (shows 33, but has 35)
- University Center for Human Values (shows 0, but has 11)

**Note:** These are the count differences I found using the UI. However, the numbers should be checked internally to be certain all counts are made correct and no assets are missing from the collection display. 

## Acceptance Criteria:

- [x] Counts are checked and verified, there aren't missing items from any collection
- [x] The counts will be corrected to show the correct amount for each collection

**Comment by hhkitsune** [comment]
@jrgriffiniii FYI, this is the problem with OAR/DSpace I had mentioned in the meeting.

**Comment by jrgriffiniii** [comment]
This should also confirm that the results on the Collection show page are valid.

**Comment by jrgriffiniii** [comment]
The collection members are rendered using database queries within interfaces such as  https://oar.princeton.edu/handle/88435/pr1mw2m (hence, these should be accurate), while the item count for the https://oar.princeton.edu/collection-list interface is populated using other mechanisms.

**Comment by jrgriffiniii** [comment]
https://github.com/PrincetonUniversityLibrary/princeton-5/tree/oar-TEST-fix-collection-count resolves most of this issue, however, there is still one final bug affecting the collection member item total within the Collection show page.

**Comment by jrgriffiniii** [comment]
I have been able to isolate https://github.com/PrincetonUniversityLibrary/princeton-5/commit/28d4c7dc4dc8584b3d56f506863e0573501b31fe#diff-b31192a1c4cab83405c6a20f9c6704c3dabe1a627ecb7efc67638497b51808bd as the area of the source code base where the query is failing (some time was consumed attempting to trace this through the logging). I am looking to try and implement a remedy for this now.

**Comment by jrgriffiniii** [comment]
While trying to resolve this as a bug, it appears that entirely rebuilding the Solr Index using (`$ /dspace/bin/dspace index-discovery -b`) is also going to be required.

**Comment by jrgriffiniii** [comment]
This is indeed what is going to be required for fully resolving this issue. I shall finalize this by opening pull requests for the source code changes.

**Comment by jrgriffiniii** [comment]
The reindexing is being finished for the deployments before this is shared for review with the stakeholders.

**Comment by jrgriffiniii** [comment]
For the production, staging, and development environments, the reindexing is now finished.
