### ISSUE TITLE
Refresh task pool for rflewell

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#718]
The user rflewell was recently added to the groups Lib_DigPubs_Submitters, Lib_DigPubs_Reviewers, and Lib_DigPubs_Approvers to mirror the access of the user debraski as requested.  The user rflewell's task pool is still empty, likely due to the fact that tasks in the pool were added prior to their being added to the DSpace group.

Is there a way that we can refresh rflewell's task pool so that they have visibility for the tasks in this group?

**Comment by jrgriffiniii** [comment]
I am unable to determine why, however, I cannot immediately retrieve the `WorkflowItem` objects associated with the user accounts `debraski` and `connell`:

```
jruby-9.2.13.0 :008 > ep2 = Java::OrgDspaceEperson::EPerson.findByEmail(DSpace.context, 'debraski@princeton.edu')
 => #<Java::OrgDspaceEperson::EPerson:0x49c17ba4>
jruby-9.2.13.0 :009 > workflow_items = Java::OrgDspaceWorkflow::WorkflowItem.findByEPerson(DSpace.context, ep2)
 => org.dspace.workflow.WorkflowItem[]@3c79088e
jruby-9.2.13.0 :010 > workflow_items.to_a.map { |wfi| wfi.add_task_pool_user('rflewell@princeton.edu') }
 => []
jruby-9.2.13.0 :011 > ep2 = Java::OrgDspaceEperson::EPerson.findByEmail(DSpace.context, 'connell@princeton.edu')
 => #<Java::OrgDspaceEperson::EPerson:0x44784e2f>
jruby-9.2.13.0 :012 > workflow_items = Java::OrgDspaceWorkflow::WorkflowItem.findByEPerson(DSpace.context, ep2)
 => org.dspace.workflow.WorkflowItem[]@5f2de715
jruby-9.2.13.0 :013 > workflow_items.to_a.map { |wfi| wfi.add_task_pool_user('rflewell@princeton.edu') }
 => []
jruby-9.2.13.0 :014 > workflow_items.to_a
 => []
```

**Comment by jrgriffiniii** [comment]
I apologize, I have found the proper approach, `rflewell` should have their task pool refreshed properly now.

**Comment by jrgriffiniii** [comment]
This has been confirmed by the user as resolved.
