### ISSUE TITLE
Create admin user for Thesis Central feature review

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#720]
Pin Lo (netID: pl1893) needs an admin account in http://thesis-central.princeton.edu/ so that he can do a feature review for a meeting with library IT leadership and stakeholders on Wednesday this week. 

Please create account for Pin Lo with admin privileges.

**Comment by jrgriffiniii** [comment]
The user account has been successfully added, I am now triggering the rebuilding of the index.

**Comment by jrgriffiniii** [comment]
The user account now appears where expected, and has `administrator` privileges as required:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/eba5ff4b-cd42-43fe-807b-b7f3114b20e0)
