### ISSUE TITLE
Import the January 2023 Dissertations into DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#723]
This was requested with the following:

> Attached is the January 2023 degree list of dissertations that I just delivered to ProQuest. Could the dissertations please be imported to DataSpace by mid-month—Feb. 15?

## Acceptance Criteria
- [x] Import dissertations
- [x] Create a new master's department for Computer Science and import Yuxuan Zhang's thesis into it
- [ ] Once we have the latest shipment of documents, put one of them here: https://drive.google.com/drive/folders/1nngkbAXSGUKLlje2beDhkBqRjKP3Bmnk

Docs here: 
* https://pulibrary.github.io/etd_transformer/process-masters-theses.html 
* https://pulibrary.github.io/etd_transformer/add-new-collection.html)

**Comment by jrgriffiniii** [comment]
Currently, there is an Item which shall require a meeting (or further discussion) with Lynn Durgin, addressing the following:

> Please note, this batch also includes one Master’s thesis—by Yuxuan Zhang. It will require a new department listing in the Master’s collection—for computer science. Perhaps we should hold off on this one until we can discuss?

**Comment by bess** [comment]
Attaching the import file here: 
[Jan2023ETDAdminReport.xlsx](https://github.com/pulibrary/dspace-development/files/10569708/Jan2023ETDAdminReport.xlsx)

**Comment by bess** [comment]
Update: 
The ProQuest dissertations are not on the server. The IP address on the server changed behind the scenes and I suspect that we have a reoccurance of something that happened in January 2022, which is that ProQuest had their automated system transfer the files, the transfer failed, and they didn't notice.

I talked to Francis about this and we've restored connectivity for the system, and he's going to talk to Steph about how to keep that system more stable (we will need to pay for a permanent IP address). 

I've emailed ProQuest (message pasted below) and hopefully they will respond soon and re-send the missing files:

> 
> 
> Dear ProQuest Dissertation Service,
>  
> I am writing from Princeton University Library. We have an automated system set up with you whereby theses are transferred to our SFTP server on a regular basis. Sometimes, something goes wrong and we have to re-send the theses (see attached email chain about when this happened last, about a year ago).
>  
> We recently experienced some disruption in our infrastructure and I believe this has led to another missed shipment of dissertations. Would you please re-send the 57 dissertations that were most recently transferred to Princeton University Library? I am attaching a spreadsheet of the missing documents.
>  
> Thank you in advance!
> Bess Sadler
> Research Data Infrastructure Developer
> Princeton University Library

**Comment by bess** [comment]
Hi Bess,

It looks like something may have changed on your end. Here is the error message we get when we try to connect:
![Image_2023-02-08_17-38-29](https://user-images.githubusercontent.com/65608/217848989-cfb3f602-6a0a-41a0-a55d-c23d3d7a0529.png)



Check with your IT Team. Once they think they have it fixed, let me know and we will run another test and then redeliver the dissertations you need. :)

Sincerely,
Carl

**Comment by bess** [comment]
Hi Bess,

Sure thing! We are trying to connect from the IP address is: 165.215.208.20

Sincerely,
Carl
--------------- Original Message ---------------
From: Bess O. Sadler [[bess.sadler@princeton.edu](mailto:bess.sadler@princeton.edu)]
Sent: 2/9/2023 4:36 PM
To: [disspub@proquest.com](mailto:disspub@proquest.com)
Subject: Re: Missing ProQuest dissertations Jan 2023

Dear Carl,

 

Would you please send us the IP address (or range) that you’re trying to connect from? We’ll need to enable that in our firewall.

 

Thank you!

Bess

**Comment by bess** [comment]
We believe the issue has been fixed on our end. I asked them to re-send on 2/14 and again on 2/17: 

> 
> Hey, Carl. Just following up, as I haven’t heard back. Would you please try sending these dissertations again and let me know if the connection works now? If it still doesn’t work, can we please set up a real-time debugging session between my people and your people so we can get this ironed out quickly? 
> 
> Thanks!
> Bess Sadler
> Princeton University Library 
> 
> From: Bess O. Sadler <bess.sadler@princeton.edu>
> Date: Tuesday, February 14, 2023 at 1:58 PM
> To: disspub@proquest.com <disspub@proquest.com>
> Subject: Re: Missing ProQuest dissertations Jan 2023
> Hey, Carl.
>  
> Would you please try sending these again? This IP address should now be enabled in our system.
>  
> Thanks,
> Bess
>  
>

**Comment by bess** [comment]
😭 Still not working as of Friday Feb 24.
I'm going to try to broker a real-time session between @kayiwa and the ProQuest team to figure this out.
> Hi Bess,
> 
> 
> Please accept my sincere apologies for this delay! Carl is out of the office this week, and I'm happy to step in to assist while he is away. 
> 
> Our developers are still unable to connect to your server. They are getting a "no hostkey alg" message.
> 
> What days/times next week would work for you to meet with our developers? I'll be happy to pass that information along and try to set something up.
> 
> Thank you!
> 
> Kind regards,
> 
> Maddie (she/her) – Author & School Relations
> ProQuest | 789 E. Eisenhower Parkway | Ann Arbor, MI USA 48106-1346 | 800-521-0600 press 2, then 1
> Visit our Knowledge Base <https://support.proquest.com/> for additional information.
> Visit our Status Page <https://status.proquest.com/> to receive updates on planned/unplanned outages.

**Comment by bess** [comment]
I've reserved the following times for potential proquest troubleshooting next week and I've asked Maddie at ProQuest whether she can arrange a phone call for me, Francis, and whoever is configuring the SFTP transfer at ProQuest: 
* Monday 2/27, 1pm - 2pm
* Wednesday 3/1, 1pm - 5pm 
* Thursday 3/2, 3pm - 4pm 
* Friday 3/3, 1pm - 2pm

**Comment by bess** [comment]
We have a meeting scheduled for Wednesday 2/28 at 2:30pm

**Comment by bess** [comment]
ProQuest was unable to make an ssh key that works with our systems, so they're going to set up access for us to pull these off of their SFTP server next.

> Hi Bess,
> 
> Thanks for confirming! Deron and I will work on getting this created for you and will let you know as soon as it's accessible.
> 
> Thanks!
> Maddie
> 
> 
> --------------- Original Message ---------------
> From: Bess O. Sadler [[bess.sadler@princeton.edu](mailto:bess.sadler@princeton.edu)]
> Sent: 3/2/2023 2:19 PM
> To: [deron.masales@clarivate.com](mailto:deron.masales@clarivate.com)
> Cc: [disspub@proquest.com](mailto:disspub@proquest.com); [kayiwa@princeton.edu](mailto:kayiwa@princeton.edu)
> Subject: Re: Missing ProQuest dissertations Jan 2023
> 
> Yes, please, let’s move forward with plan B. Send us the SFTP info as soon as possible. Thank you!
>  
> Typed with my thumbs. Please excuse brevity & typos.
>
