### ISSUE TITLE
Identify and resolve the Workflow Item issues for 46830

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#732]
This was discovered by a user within the `#dspace` Slack Channel:

> There’s no way to look at an in progress submission to determine which primary collection it belongs correct, correct?
> OK. The workflow(?) ID I have is 46830
> I’m just trying to figure out why nothing happened for it for months

**Comment by jrgriffiniii** [comment]
The Item submitted appears not to have an `owner` associated with it:

```bash
jruby-9.2.13.0 :004 > workflow_item = Java::OrgDspaceWorkflow::WorkflowItem.find(DSpace.context, 46830)
 => #<Java::OrgDspaceWorkflow::WorkflowItem:0x6c518474>
jruby-9.2.13.0 :005 > workflow_item.item
 => #<Java::OrgDspaceContent::Item:0x63411512>
jruby-9.2.13.0 :006 > workflow_item.item.id
 => 150933
jruby-9.2.13.0 :007 > workflow_item.state
 => 3
jruby-9.2.13.0 :008 > workflow_item.getOwner
 => nil
jruby-9.2.13.0 :009 > workflow_item.getSubmitter
 => #<Java::OrgDspaceEperson::EPerson:0x5d5160e6>
jruby-9.2.13.0 :010 > workflow_item.getSubmitter.getEmail
 => "gkramer@princeton.edu"
```

**Comment by jrgriffiniii** [comment]
This should now be in the appropriate Task Pool for the reporting user, and I have request that they please confirm this when they are next available.

**Comment by jrgriffiniii** [comment]
The reporting user has indicated that there are now two Items within the Task Pool (where before there were none).

**Comment by jrgriffiniii** [comment]
The reporting user has indicated that there are now two Items within the Task Pool (where before there were none).

**Comment by astrochun** [comment]
Thanks for creating this ticket on my behalf

**Comment by astrochun** [comment]
> The reporting user has indicated that there are now two Items within the Task Pool (where before there were none).

To clarify: There was one before - the one submitted by the user. I see two of them now.

**Comment by jrgriffiniii** [comment]
After invoking the following, I have identified and removed the duplicate record referencing the WorkFlowItem and Item records:

```bash
dataspace_prod_db=> select p.email,t.workflow_id,w.item_id from tasklistitem as t inner join eperson as p on p.eperson_id=t.eperson_id inner join workflowitem as w on w.workflow_id=t.workflow_id where p.email='chunly@princeton.edu';
        email         | workflow_id | item_id
----------------------+-------------+---------
 chunly princeton.edu |       46830 |  150933
 chunly princeton.edu |       45390 |  144811
 chunly princeton.edu |       45554 |  146548
 chunly princeton.edu |       46830 |  150933
 chunly princeton.edu |       47508 |  165169
 chunly princeton.edu |       46878 |  152851
 chunly princeton.edu |       46872 |  121273
(7 rows)
```

**Comment by jrgriffiniii** [comment]
I am very sorry @astrochun, it currently is not displaying that it belongs to *any* collections.

Might there be one specific Collection to which it should be added?

Additionally, from my understanding, it seems as if you have reviewed the Item and that it may be prepared to be published. If this is the case, please let me know and I can publish this.

**Comment by jrgriffiniii** [comment]
Inspecting the Item briefly, https://dataspace.princeton.edu/handle/88435/dsp01x920g025r seems to be an appropriate candidate for the Collection, however I did not wish to presume this was the case.

**Comment by astrochun** [comment]
We can always place it in there and then move it if it turns out to be incorrect.

Here's what I see. I'm not sure why it shows up as "Review Submission" instead of the usual two statuses:
<img width="1163" alt="Screen Shot 2023-02-23 at 11 57 55 AM" src="https://user-images.githubusercontent.com/20305734/221004298-0ec7df88-f194-4919-9b84-9b14e868bbf2.png">

**Comment by jrgriffiniii** [comment]
Ah, I see now, this is a bug which has occurred for some other Item submissions. I can look to provide a solution in one moment.

**Comment by jrgriffiniii** [comment]
The state should be updated, and the submission should be in the appropriate Collection.

When you next have the opportunity @astrochun, might I please request that you investigate this using your user account?

Thank you again.

**Comment by astrochun** [comment]
Thanks. I do see this. Let's keep this ticket open for the mean time and I'll work with the reviewer and the researcher. Hoping to have it publish and then will revisit to close this ticket.

**Comment by jrgriffiniii** [comment]
You're welcome, thank you again.

Just to ensure that the activity on this issue is logged, this bug was related to a misconfigured workflow step applied to the parent Collection. The Accept/Reject step must be deleted.

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/5b7c822c-0921-48e1-8f58-22a76dbb5259)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/37470e6a-1628-4499-9a8d-bb6352806500)

This has occurred elsewhere, and much of this configuration has been either inherited from the legacy system (which was migrated from the original OIT infrastructure), or, it is possible that during the migration certain configuration settings may not have been properly set for the new deployments.

**Comment by astrochun** [comment]
> You're welcome, thank you again.
> 
> Just to ensure that the activity on this issue is logged, this bug was related to a misconfigured workflow step applied to the parent Collection. The Accept/Reject step must be deleted.
> 
> ![image.png](https://camo.githubusercontent.com/557d22c4c2b31e0d706875566687dae51f13f64497035b481533791e62a599a8/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562356236616564393831633332303463396564303663382f35623763383232632d303932312d343865312d386635382d323261373664626235323539)
> 
> ![image.png](https://camo.githubusercontent.com/e7097c94dcea11fe8dd9a3420fba996656ce2cd87e1e0eef9da700c74163f661/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562356236616564393831633332303463396564303663382f33373437306536612d313632382d343439392d396138642d626236333532383036353030)
> 
> This has occurred elsewhere, and much of this configuration has been either inherited from the legacy system (which was migrated from the original OIT infrastructure), or, it is possible that during the migration certain configuration settings may not have been properly set for the new deployments.

Computational Sciences was one that was created recently so it's possible that I made the mistake, so I will take onus on my error. It was one of the first collections that I created.
