### ISSUE TITLE
Import dissertations records for March 2023 into DataSpace

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#742]
Per Lynn Durgin's email below, import these dissertations into DataSpace by April 26.

> Attached please find a list of the most recent batch of dissertations (no master’s theses this time) for importing into DataSpace. I believe there is a new process for retrieving the files, rather than an ftp delivery.  Could these be imported into DataSpace within two to three weeks—by 4/26/23?

ETDAdmin report for this batch - 
[ETDAdminReport.xlsx](https://github.com/pulibrary/dspace-development/files/11172268/ETDAdminReport.xlsx)

**Comment by carolyncole** [comment]
https://github.com/pulibrary/rdss-catchall/issues/89
