### ISSUE TITLE
User reported errors when attempting to access ThesisCentral (production) using the Chrome browser

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#744]
The following was reported at Thursday, April 20, 2023 11:44 AM
> I had a student say she is getting an error in Thesis Central-- Error reading from remote server—today. Have you heard of this happening?

It should be noted that this was resolved with the usage of Safari:

> She was using Chrome but tried Safari and said it was now working for her. Hopefully it was an issue on her end. Thank you!

**Comment by kelynch** [comment]
I don't know that this is workable, is it?

**Comment by kelynch** [comment]
Closing, user was able to accomplish their task in another browser.
