### ISSUE TITLE
Users report that e-mail notifications contain missing information for ThesisCentral submissions

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#747]
The following errors were reported:

> I received an inquiry today from a student who submitted his thesis and received a submission confirmation email, but the document title didn’t come in through the email (see below). I submitted a test submission in production after receiving this and my title did come through. There don’t seem to be any other issues with the site from what I can tell, but I wanted to make you aware of this in case it might indicate a larger issue.

**Comment by kelynch** [comment]
Factor in the need for email notifications in migration to a new application for thesis submissions.
