### ISSUE TITLE
DataSpace - cannot upload files

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#755]
Users are reporting being unable to upload files -- one user reported being unable to upload a 14.6MB PDF and another a 7MB PDF.

A 336kb PDF was successfully uploaded by another user.

When attempting to load one of the failing files, the following errors display:
<img width="640" alt="Screenshot 2023-05-05 at 3 00 29 PM" src="https://user-images.githubusercontent.com/7795797/236546934-c90aac28-61c5-4857-87ef-e53688fdad18.png">

**Comment by carolyncole** [comment]
This was done for PDC in the load balancer: https://github.com/pulibrary/princeton_ansible/pull/3268/files
See https://github.com/pulibrary/pdc_describe/issues/290
