### ISSUE TITLE
OAR: New Collections

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#757]
## Due Dates

**Proposed Due Date:** Not on fire, but needed in early-mid June

## Description:

We have three new collections that need to be added to the Open Access Repository. These are the following to add:
- Future of Children Policy Briefs
- Future of Families and Child Wellbeing Study Research Briefs
- New Jersey Families Study Newsletters

## Acceptance Criteria:

- [ ] Three new collections are added to OAR (See labels above)

**Comment by jrgriffiniii** [comment]
I apologize for the delay in resolving this, please find the new Collections at the following URLs:

- [Future of Children Policy Briefs](https://oar.princeton.edu/handle/88435/pr11n7xm7k)
- [Future of Families and Child Wellbeing Study Research Briefs](https://oar.princeton.edu/handle/88435/pr1ww7702m)
- [New Jersey Families Study Newsletters](https://oar.princeton.edu/handle/88435/pr1s46h58x)

Please let me know should there be any modifications required, or should the authorization policies for each Collection need to be modified.
