### ISSUE TITLE
OAR: FAQ page link

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#759]
## Due Dates

**Proposed Due Date:** Not on fire

## Description:
We need a link added to the top of the OAR.princeton.edu page that will say: FAQ. This link will go to the following page: https://library.princeton.edu/services/scholarly-communications/oar-faq

## Acceptance Criteria:

- [ ] Link is added to the navigation bar at the top of the repository page
- [ ] Link goes to this address: https://library.princeton.edu/services/scholarly-communications/oar-faq

**Comment by kelynch** [comment]
Deferring until we determine the future platform for the OAR.
