### ISSUE TITLE
DataSpace collections for academic departments and senior theses are sometimes ambiguous

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#761]
On 06/13/23, the following was reported on Slack:

> A student has reported seeing no available senior theses in Economics in Dataspace. The student sent a screen shot.
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/96f0096f-f723-4737-ba3a-6664a4297e88)
> I'm unclear on what the problem is, as other department theses are reportedly available.

Should there be any adjustments applied to the titles for Communities and Collections for DataSpace?

**Comment by kelynch** [comment]
Given the trajectory for DataSpace, I think we can safely close this at this time.  If users go to the wrong collection by mistake in the meantime, they can be directed appropriately by a staff member.
