### ISSUE TITLE
Ensure that the May 2023 ETDs are imported into DataSpace by 07/08/23

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#764]
The following was requested:

> I have recently delivered the May 2023 degree Master’s theses and dissertations, which includes 13 master’s theses and 177 dissertations.
> Could these be imported by July 8?
> We will need to create a new collection for Operations Research and Financial Engineering and Civil and Environmental Engineering  in the Master’s thesis community.

- [x] Import May 2023 dissertations and masters theses to DataSpace
- [x] Report back to Lynn when it's done
- [x] Finish by July 8

Spreadsheet here: 
[ETDAdmin Report May 2023.xlsx](https://github.com/pulibrary/rdss-catchall/files/11805224/ETDAdmin.Report.May.2023.xlsx)

**Comment by bess** [comment]
Dear Lynn,
 
I’ve ingested these ETDs. There were 13 masters’ theses, as expected, but only 175 (not 177) dissertations in the transfer from ProQuest. I’m sorry, but I don’t have a way to know what’s missing.
 
The new collections under Masters’ Theses were created as requested.
 
The files were transferred to us from Proquest on 3 July 2023 and ingested on 6 July 2023.
 
Thanks,
Bess
