### ISSUE TITLE
DataSpace: Notice of Change for research data users (DataSpace to PDC)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#765]
## Priority
Needed ASAP to promote the change in platforms for PDC's launch

## Description:
We need to announce the change in platform to our current users for research data in DataSpace.

### Please add banner or other notices in DataSpace for the following locations:
- When logged in to deposit: “dataspace.princeton.edu/mydspace”
- Homepage: dataspace.princeton.edu

### Text to use for notices
- Princeton’s Research Data Repository is becoming the Princeton Data Commons! See [the PRDS website](https://researchdata.princeton.edu/introducing-princeton-data-commons) for more information.

## Acceptance Criteria:
- [ ] Notice(s) are applied where depositors will see them.
- [ ] Notice(s) are applied to the homepage for everyone to see
- [ ] The text and link provided above are used for notice messaging
- [ ] Notices have a highlight color that is pleasing but also grabs the attention of the users

**Comment by kelynch** [comment]
This has been deployed for review at https://dataspace-dev.princeton.edu/ 

Screenshot is also available below: 
<img width="1182" alt="Screenshot 2023-06-27 at 2 37 26 PM" src="https://github.com/pulibrary/dspace-development/assets/7795797/d331b37f-6fed-40b9-a9b3-9121f263332e">

Please review and let me know if this is sufficient to be deployed to staging and production when you get a chance.

**Comment by kelynch** [comment]
Leave message for all users (logged in and external) on the homepage.

Also add to the submit page for logged in users (https://dataspace-dev.princeton.edu/submit)

Additional CSS changes: 

```CSS
.alert {
    background-color: #F4EA48;
    font-weight: bold;
    border: 2px #E6C700 solid;
} 
```

**Comment by kelynch** [comment]
@hhkitsune please see the new code deployed at https://dataspace-dev.princeton.edu/ with requested changes to the homepage and the submit page: https://dataspace-dev.princeton.edu/submit

Screenshots: 

![Screenshot 2023-06-28 at 4 21 46 PM](https://github.com/pulibrary/dspace-development/assets/7795797/76c34fe9-361f-4ada-a235-4cff266f664a)

![Screenshot 2023-06-28 at 4 21 37 PM](https://github.com/pulibrary/dspace-development/assets/7795797/725e29ee-dd93-47d1-a4ba-f1f6b7873ba0)
