### ISSUE TITLE
DataSpace: List of research data depositors for the past year

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#766]
## Description:
PRDS needs the contact information for research data depositors from the last year. They will email a notice of the change from DataSpace to PDC with information about PDC to these users. Please provide this listing to Neggin.

## Acceptance Criteria:
- [ ] Provide Neggin the list of research data depositors for the past year

**Comment by astrochun** [comment]
@neggink I was wondering for PPPL researchers whether that email can come from my office. If we can somehow coordinate, that would be great.

**Comment by neggink** [comment]
@astrochun We can absolutely coordinate on the email communications!

**Comment by kelynch** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1BVTLBY9TrpmN4DacI9FdaWxU5Fs1WSGKqtdSFaY5iIg/edit#gid=551457646) provided to Neggin, Chun, and Hannah via email

**Comment by kelynch** [comment]
Example of method used via the DSpace CLI to retrieve this information:

```
coll = DSpace::CLI::Collection.find_by_handle("88435/dsp01th83m2429")

items = coll.get_all_items

items.each do |i|
    date_val = i.submitter.getLastActive.nil? ? 'NA' : i.submitter.getLastActive.toLocalDateTime.to_s.split("T").first 
    puts "#{i.submitter.full_name},#{i.submitter.email},#{date_val}"
end 
```

I used [this collection](https://github.com/pulibrary/pdc_discovery/blob/main/config/collections.csv) to get all of the handles needed.
