### ISSUE TITLE
Track down wayward dissertations

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#786]
Three dissertations ended up in the wrong queue:
1. FIGHTING THE OTTOMAN GREAT WAR, Coskuntuna, Duygu
2. Feeling Like a State: Anxiety and Optimism in the late-Ottoman Empire, Pelling, Jamie Heather
3. Coalescence of the Empire: Administration of the Provincial Economy in Ottoman Damascus, 1820-1860, Bozluolcay, Murat

All somehow ended up in Kevin Connell's archiving queue instead of the dissertation collection they were meant for.

- [x] Figure out why, if possible
- [x] Resubmit them and see that they get where they were supposed to go

**Comment by kelynch** [comment]
Kevin Connell rejected them, so they are back in the unfinished submissions area of the site.  I will next reassign these to myself to examine and process.

**Comment by kelynch** [comment]
These dissertations were in the correct collection ([Near Eastern Studies](https://dataspace.princeton.edu/handle/88435/dsp01b8515n39n)) but for some reason, this collection has submitters and reviewers groups configured in DataSpace for it, see below:
![Screenshot 2023-10-27 at 10 49 08 AM](https://github.com/pulibrary/dspace-development/assets/7795797/4c55cfac-3a63-4fb1-b3bb-03915bd4f7be)

Groups in the "Accept/Reject/Edit Metadata" group are defined as follows:
![Screenshot 2023-10-27 at 10 50 19 AM](https://github.com/pulibrary/dspace-development/assets/7795797/a6138ea6-9c2b-4522-ad57-4955b2cb8f59)

I spot-checked several other collections within dissertations, and they are all configured as follows, with no groups defined for any sort of manual intervention (which is what I believe we would expect for all collections):
![Screenshot 2023-10-27 at 10 48 58 AM](https://github.com/pulibrary/dspace-development/assets/7795797/17f1c904-da5a-4360-8b0a-19555fc277cc)

For next steps, I'll check in with RDSS and Special Collections to see if there is a known reason for the difference between Near Eastern Studies and other dissertation collections and update here with more information.

**Comment by kelynch** [comment]
RDSS confirmed not knowing why this collection would be different from the others.  I have a question out to Lynn and Christa now to see if they know.

**Comment by kelynch** [comment]
Special Collections also confirmed not knowing why this collection would be different.  We can either reconfigure the collection to remove reviewer and submitter groups, or add dissertation admins to these groups, then resubmit these dissertations from Bess's account in the web UI (they were sent back to Unfinished Submissions when Kevin Connell rejected them).  We are meeting with Special Collections later this week to determine what we need to do about the groups, and will open a new ticket for last steps.

**Comment by kelynch** [comment]
The Near Eastern Studies collection should be reconfigured to match the other dissertation collections, and the dissertations should be published.  @bess, is it more straightforward if we resubmit these dissertations manually in the DataSpace UI and one of us can approve them (I can temporarily add myself to the reviewers so we can do this) and then remove the groups, or is it preferable for the groups to be removed and we reprocess the dissertations through the standard workflow?  I'm a little concerned we'll create duplicates or just lose access to the three that are now in your submission pool if we do the latter but this may not be a risk.

**Comment by kelynch** [comment]
I reconfigured the Near Eastern Studies collection to only have me as an approver temporarily so that we can get these dissertations published.  @bess whenever you get a chance, per our chat on Slack can I ask you to please resubmit those dissertations that are in your "Unfinished Submissions" section of your dashboard in the DataSpace UI, and then I'll approve them and readjust the collection?  Happy to pair on this if it's helpful.

**Comment by kelynch** [comment]
Bess was able to resubmit these.  I approved them:

* https://dataspace.princeton.edu/handle/88435/dsp01db78tg347 
* https://dataspace.princeton.edu/handle/88435/dsp018k71nm41b
* https://dataspace.princeton.edu/handle/88435/dsp014x51hn338

**Comment by kelynch** [comment]
I removed the submitters and reviewers/approvers groups from the [Near Eastern Studies collection in DataSpace](https://dataspace.princeton.edu/handle/88435/dsp01b8515n39n).  This should hopefully prevent submissions from getting stuck in the future.
