### ISSUE TITLE
DSpace prod is out of disk space

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#794]
<img width="1049" alt="Screenshot 2023-12-04 at 12 10 34 PM" src="https://github.com/pulibrary/dspace-development/assets/65608/443643ab-afa3-4063-be91-7368631ef580">

gcp-dataspace-prod1 can't run commands right now because the root disk is full. :( 

<img width="1411" alt="Screenshot 2023-12-04 at 12 19 35 PM" src="https://github.com/pulibrary/dspace-development/assets/65608/edd816e1-d4e1-48d1-9488-2ddcd278596a">

**Comment by bess** [comment]
Fixed! Thank you, @kayiwa :) 

<img width="1049" alt="Screenshot 2023-12-05 at 8 32 57 AM" src="https://github.com/pulibrary/dspace-development/assets/65608/acb269ac-b716-49f9-973c-4bae27d059a2">

**Comment by jrgriffiniii** [comment]
I apologize for the delay in looking to clean these files, I have managed to reduce the disk space consumed to the following:

```bash
dspace@gcp-dataspace-prod1:~$ df -H
Filesystem                    Size  Used Avail Use% Mounted on
udev                          3.9G     0  3.9G   0% /dev
tmpfs                         781M  807k  780M   1% /run
/dev/mapper/libserv--vg-root   41G   31G  8.4G  79% /
tmpfs                         4.0G     0  4.0G   0% /dev/shm
tmpfs                         5.3M     0  5.3M   0% /run/lock
tmpfs                         4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/sda1                     493M  216M  252M  47% /boot
/dev/sdb                      4.3T  2.0T  2.4T  46% /mnt/disks/dataspaceproddatastore
tmpfs                         781M     0  781M   0% /run/user/1000
```

Please let me know should I be able to assist in any manner, or should this occur again. Thank you for your patience.
