### ISSUE TITLE
Changes to firewall rules needed?

### ISSUE THREAD

**Issue by bess** [pulibrary/dspace-development#800]
Steph sent this message via slack:

> Starting tomorrow, OIT is implementing the new Undergraduate and Graduate Student segments for eduroam. John K added these ranges to the Palo Alto firewall in early Dec 2023. If you have any local firewall rules on systems that students need to access, please make sure they allow the following addresses:
> Undergraduate segment: 10.48.0.0/15 ip4-wifirestricted03
> Graduate segment: 10.50.0.0/15 ip4-wifirestricted04

@jrgriffiniii Do we need to do anything to ensure continued access to DSpace systems?

**Comment by jrgriffiniii** [comment]
From what I can recall, I do not believe that these rules need to be updated, but I can verify this momentarily.

**Comment by jrgriffiniii** [comment]
This subnet mask should cover all possible addresses: https://github.com/PrincetonUniversityLibrary/princeton-5/blob/dataspace-prod/dspace/config/modules/authentication-ip.cfg#L305

Thank you very much for creating this. Should there be any incidents (there should not be), I can definitely look to reopen this.
