### ISSUE TITLE
Change DataSpace banner to include more information of disabled submissions

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-development#802]
We are beginning to shutdown submissions to DataSpace for specific collections. As such, the banner should be adjusted to include the following:

"If you don't see the collection when you're submitting, it is because we have disabled submission for that collection and require submission to PDC at the following website: https://datacommons.princeton.edu/describe/"

**Comment by kelynch** [comment]
@matthewjchandler Per today's prioritization meeting, please have a look at this when you get a chance and give feedback on the wording/approach.

**Comment by matthewjchandler** [comment]
I like Chun's suggestion, and I would build on it a bit. Here's new language I came up with:

"Princeton’s Research Data Repository is becoming the Princeton Data Commons! As we transition, you may not see some of the collections you were once able to submit to in DataSpace, and that means [Princeton Data Commons](https://datacommons.princeton.edu/describe/) is ready for you. For more information, please visit the [Princeton Research Data Service website](https://researchdata.princeton.edu/introducing-princeton-data-commons)."

**Comment by matthewjchandler** [comment]
Just to clarify on this, does the link to PDC from the updated banner take everyone to PDC Describe, and then allow anyone with a NetID to submit? If so, I think that undermines our intentions for a soft launch. With apologies, I think I have to revise my prior comment and suggest that we remove all links to PDC Describe until PRDS is ready.

**Comment by matthewjchandler** [comment]
@astrochun I'm thinking we could adjust the message to direct PPPL users toward PDC as appropriate, while signaling to others that they should keep using DataSpace for now. Do you have a website up already that guides PPPL folks on using PDC? If so, I'd suggest linking to that. If not, we can just clarify the message in the banner.

**Comment by astrochun** [comment]
> @astrochun I'm thinking we could adjust the message to direct PPPL users toward PDC as appropriate, while signaling to others that they should keep using DataSpace for now. Do you have a website up already that guides PPPL folks on using PDC? If so, I'd suggest linking to that. If not, we can just clarify the message in the banner.

Not immediately. We're doing a full refresh of our website and then would tackle the need to update pages for PDC information. An option that we can consider is to modify the banner to tell PPPL researchers to reach out to us at publications@pppl.gov

**Comment by matthewjchandler** [comment]
@astrochun may I suggest this new banner language:

> Princeton's Research Data Repository is becoming the Princeton Data Commons! As we transition, you may not see some of the collections you were once able to submit to in DataSpace, and that means Princeton Data Commons is ready for you. If you are intending to publish from the Princeton Plasma Physics Laboratory and you have questions about the new submission process, please contact [publications@pppl.gov](mailto:publications@pppl.gov). For all other questions about getting started with submissions to Princeton Data Commons, please contact [prds@princeton.edu](mailto:prds@princeton.edu). For more information, please visit the [Princeton Research Data Service website](https://researchdata.princeton.edu/introducing-princeton-data-commons).

**Comment by matthewjchandler** [comment]
@astrochun Do you have a preferred modification? E.g. publications[at]pppl[dot]gov? Or just remove the mailto link? PRDS is usually pretty free about putting its mailto email address up online, and we deal with the spam.

**Comment by astrochun** [comment]
> @astrochun Do you have a preferred modification? E.g. publications[at]pppl[dot]gov? Or just remove the mailto link? PRDS is usually pretty free about putting its mailto email address up online, and we deal with the spam.

Removing the mailto should suffice. I don't want it to be more cumbersome for the researchers.

**Comment by matthewjchandler** [comment]
@jrgriffiniii Here's the new text we want for the DataSpace banner ASAP:

> Princeton's Research Data Repository is becoming the Princeton Data Commons! As we transition, you may not see some of the collections you were once able to submit to in DataSpace, and that means Princeton Data Commons is ready for you. If you are intending to publish from the Princeton Plasma Physics Laboratory and you have questions about the new submission process, please contact publications@pppl.gov. For all other questions about getting started with submissions to Princeton Data Commons, please contact prds@princeton.edu. For more information, please visit the [Princeton Research Data Service website](https://researchdata.princeton.edu/introducing-princeton-data-commons).

### Completion Criteria
- [ ] The new text reads as in the block quote in this comment
- [ ] The email addresses are NOT clickable links in the banner (despite how they're rendered here in GitHub)
- [ ] The link to the "Princeton Research Data Service website" (https://researchdata.princeton.edu/introducing-princeton-data-commons) IS clickable, as rendered here in GitHub

**Comment by jrgriffiniii** [comment]
I apologize for the delay, please find a screenshot from the current deployment using the `dev` environment (https://dataspace-dev.princeton.edu/):

![image](https://github.com/pulibrary/dspace-development/assets/1443986/f00a56d4-177d-4364-8440-abe451fd998c)

**Comment by matthewjchandler** [comment]
Looks great, thank you @jrgriffiniii !

**Comment by astrochun** [comment]
Looks good. Thanks! 👍
