### ISSUE TITLE
[dataspace] Prevent new submissions to research data collections

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#819]
## Due Dates

**Proposed Due Date:** April 23, 2024

Reason: Users were informed on April 15, 2024 that DataSpace was closed. We want to enforce this ASAP.

## Description:

Per [ADR 0014](https://github.com/pulibrary/pdc_describe/blob/main/architecture-decisions/0014-transitioning-collections-from-dataspace-to-pdc-describe.md) in PDC Describe, our decision is to begin shutting down research data collections in DataSpace today, April 16, 2024. The first step is to prevent new submissions to the research data collections listed in the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo) (rows 16-35).

## Acceptance Criteria:

- [x] Prevent new submissions to all PRDS-curated research data collections listed in the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo) (rows 16-37)
- [x] Mark the field "Submissions Turned off in DataSpace?" to "Yes" for each closed collection in the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo) (rows 16-37)

**Comment by kelynch** [comment]
Reference: https://github.com/pulibrary/dspace-development/issues/808

**Comment by kelynch** [comment]
Done and relayed to @matthewjchandler
