### ISSUE TITLE
[dataspace] Find out which research data collections still have submissions in process after closing date

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#820]
## Due Dates

**Proposed Due Date:** April 23, 2024

Reason: Users were informed on April 15, 2024 that DataSpace was closed. We want to clear out any unfinished submissions ASAP.

## Description:

Per [ADR 0014](https://github.com/pulibrary/pdc_describe/blob/main/architecture-decisions/0014-transitioning-collections-from-dataspace-to-pdc-describe.md) in PDC Describe, our decision is to begin shutting down research data collections in DataSpace today, April 16, 2024. The first step was to prevent new submissions to the research data collections (#819). The second step is to find any unfinished submissions in the research data collections, as listed in the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo) (rows 16-35), so that we can decide how to clear them out.

## Acceptance Criteria:

- [ ] Find any unfinished submissions within any of the PRDS-curated research data collections listed in the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo) (rows 16-35)
- [ ] Collate a list of all unfinished submissions into a new sheet within the [DataSpace Collections Migration Tracking sheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo)

**Comment by kelynch** [comment]
@jrgriffiniii When you're back in the office, can we pair on this?  I'm having some difficulty determining which collections submissions in-process are being sorted into.

**Comment by kelynch** [comment]
I will check with Matt to see if he still needs this and will add it to the next sprint if so.

**Comment by matthewjchandler** [comment]
Yes, it would be good to have this added to the next sprint backlog. It will be helpful as we close things out with the migration.

**Comment by kelynch** [comment]
This appears to no longer be necessary, as I just got word that the last researcher's submission that was in process has been dealt with by PRDS in DataSpace.
