### ISSUE TITLE
Adjust collection submission item template for International Journal of Arts Management

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#843]
The [International Journal of Arts Management](https://dataspace.princeton.edu/handle/88435/dsp01gb19f913s) collection should have the serials item template, as shown in the screenshot below:

![thumbnail_image002](https://github.com/user-attachments/assets/9d728361-72bd-4805-9ef7-50afebe6fefb)

**Comment by jrgriffiniii** [comment]
I have temporarily adjusted the input forms configuration XML file, but the changes proposed by https://github.com/PrincetonUniversityLibrary/princeton-5/pull/96/files are required in order to ensure that this is permanent.

**Comment by kelynch** [comment]
Thank you, James!  I've followed up with Debby regarding this and reviewed the princeton-5 changed.  I'm going to close this ticket.
