### ISSUE TITLE
[dataspace] Disable Notifications for Certain PULibrary Users

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#855]
As reported by a user, messages are being erroneously sent to certain user groups which were not sent before (this is troubling as no group membership settings have been adjusted).

**Comment by jrgriffiniii** [comment]
The following workflow configuration may well have been the cause for these notifications. I am requesting the user to test in order to confirm that error messages are no longer being erroneously sent to certain users:
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FTQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4491fc48682b574037fb7f8735f2fc30bf99bb83/image.png" alt="image.png" />

**Comment by jrgriffiniii** [comment]
The user has confirmed that notifications are now being sent as expected. I am going to proceed by leaving this unresolved before tomorrow just to be certain that no other errors related to this arise.

**Comment by jrgriffiniii** [comment]
I have been notified by `alpanam` that the configuration for the following collections also need to be verified:

- Annual report (Meghalaya State Commission for Women)
- Annual report (National Commission for Women)
- Annual report (University Grants Commission)

**Comment by jrgriffiniii** [comment]
I have found that the configurations for each of these collections are not consistent:

![image](https://github.com/user-attachments/assets/22cb93b0-1962-4222-9c08-ed840e1d1793)
![image](https://github.com/user-attachments/assets/16ccf2dc-af96-4deb-b8de-7cc8dab38b8f)
![image](https://github.com/user-attachments/assets/0e266dbc-88b2-4a26-be70-93c640ac186e)

**Comment by jrgriffiniii** [comment]
The configurations should now be identical between the three collections:

![image](https://github.com/user-attachments/assets/566c7895-dd83-46fc-9395-3aac2d02d35b)
![image](https://github.com/user-attachments/assets/3fc16abf-eaac-438d-b24e-4bafa446064a)
![image](https://github.com/user-attachments/assets/4f545406-c2ff-412b-8480-1e7937e0c2f2)

**Comment by jrgriffiniii** [comment]
This was reported by the user `temanuel` as still occurring, with the most recent incident being this afternoon.

**Comment by jrgriffiniii** [comment]
There was a mistake in communication, and this has indeed been resolved for the affected users.

**Comment by jrgriffiniii** [comment]
This is still occurring for certain users within other DataSpace collections, as reported by multiple users on 12/16/24

**Comment by jrgriffiniii** [comment]
kelynch has resolved the error for the following cases:

> The "Serials and series reports (Publicly Accessible) - Annual report (University Grants Commission)" collection still had a "Review" step defined that was mapped to the Lib_DigPub_Submitters group incorrectly.  I don't know how this would have happened in the first place, sorry, however it should be resolved now.

This has affected the following users:
- dmagier
- hyoungl
- facosta
- temanuel

**Comment by jrgriffiniii** [comment]
Reviewing Collections within the Community `Serials and series reports (Publicly Accessible) - Annual report (University Grants Commission)`, there are definitely errors and inconsistencies within each of these beyond what have been discovered. For example, one case `Serials and series reports (Publicly Accessible) - Annual Report : Sindh Agricultural and Forestry Workers Coordinating Organization` has no permissions at all set:

<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGt0Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faa0412367765fbde5fd5f0c2f999ca1cbdd6175/image.png" alt="image.png" />
<img width="1355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG90Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3db78410598808928f0288173846ce5aa01a21a0/image.png" alt="image.png" />

**Comment by kelynch** [comment]
A further audit of groups was conducted and documented in this ticket - https://github.com/pulibrary/dspace-development/issues/863
