### ISSUE TITLE
Diagnose performance issues for Dropbox API uploads

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#91]
Currently the approach for uploading files to the Dropbox API rely upon the project https://github.com/rianhunter/dbxfs

As observed in https://github.com/rianhunter/dbxfs/blob/master/dbxfs/dbxfs.py#L76, the REST requests issued in order to iterate through the contents of Dropbox Folders as directories on a file system (mounted using the FUSE) introduce a flood of REST HTTP requests when using tools such as `rsync` for file transfers.

Perhaps there is another solution for working directly with the REST API for file uploads?

**Comment by jrgriffiniii** [comment]
While I have being encountering strange and erratic behavior using the FUSE driver from within a macOS environment, I have found that attempting to reinstall [osxfuse](https://github.com/osxfuse/osxfuse/releases) has assisted slightly with this.

I was able to transfer an entire .tar.gz to https://www.dropbox.com/s/qnpuhcbj9mh54ow/DNN_Model_Training.tar.gz?dl=0. Unfortunately, attempting this with the Two_State_Fit .tar.gz file yields only an empty file. I will attempt to upload this manually by using the web interface.

**Comment by jrgriffiniii** [comment]
Using the [sshfs](https://github.com/libfuse/sshfs), I am now attempting to manually transfer the .tar.gz files directly to Dropbox.

**Comment by jrgriffiniii** [comment]
The approximation for a 8GB .tar.gz upload is 2 days, as indicated by the Dropbox web client:

![image](https://user-images.githubusercontent.com/1443986/88081581-91123a80-cb4e-11ea-9987-47f88d71efc6.png)

**Comment by jrgriffiniii** [comment]
The transfer seems to have stalled with the message `1 second left` - this has been the status of the upload for several hours:

![image](https://user-images.githubusercontent.com/1443986/88179269-a42e1480-cbf9-11ea-8a8a-3878bf135f9b.png)

**Comment by jrgriffiniii** [comment]
I am attempting another file transfer using a combination of the SSHFS and the Dropbox browser client.

**Comment by jrgriffiniii** [comment]
This .tar.gz file was successfully uploaded - approximately 10 hours were needed for this be successfully uploaded using the browser UI:

![image](https://user-images.githubusercontent.com/1443986/88245057-b6dd3380-cc63-11ea-8ace-d7d184c0fb0c.png)

**Comment by jrgriffiniii** [comment]
Perhaps Google Drive could also suffice as an alternative storage solution.

**Comment by kmcelwee** [comment]
The integration of Globus obviates this I hope!
