### ISSUE TITLE
Upgrade to Vireo 4.0.x Release

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#94]
Thesis Central is currently running on Vireo release 3.0.6. Given that Vireo's latest release has been 4.0.0 (and deprecates the Play framework in favor of Spring MVC), upgrading this should be evaluated at some point in time.

**Comment by kmcelwee** [comment]
Since we aren't responsible for vireo, presumably this doesn't apply to us anymore?

**Comment by jrgriffiniii** [comment]
This is no longer going to be possible or necessarily within scope.
